### PR TITLE
fix units for vector hh output

### PR DESCRIPTION
**Pull request by swensosc**
### Description of changes
Change units on vector history fields for hillslope variables
### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?
no
Any User Interface Changes (namelist or namelist defaults changes)?
no
Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by wwieder** [comment]
@swensosc it seems like these are b4b changes that just modify metadata on history files.  If so, @slevis-lmwg can you bring this onto the b4b-dev tag?  Is testing even needed for something this minor, @ekluzek?

**Review by slevis-lmwg — APPROVED** [review]
Thank you for these corrections @swensosc 

Seems unnecessary to test this, but to be on the safe side I could try the "short" test-suite, to prove that nothing broke.

**Comment by slevis-lmwg** [comment]
@swensosc could you add me as collaborator, so that I may push to the PR?

Click "Settings" near the top-middle-right of this page, then click "Collaborators" and then follow the instructions.

**Comment by slevis-lmwg** [comment]
I submitted the short test-suite:
`./run_sys_tests -s clm_short -c ctsm5.1.dev176 --skip-generate`

**Pull request merged**
