### PR TITLE
Merge tag 'ctsm5.1.dev175' into b4bdev

### PR DESCRIPTION
**Pull request by slevis-lmwg**
Merge dev175 to b4bdev

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
@samsrabin @ekluzek 
I have reached step 15g in the bfb-dev instructions:
- [ ] I need approval to complete the merge.
- [ ] I need to rebase the PR so that the merge goes to the bfb-dev branch rather than to master.
- [ ] I need Erik to add dev175 to the CESM test database.
- [ ] Anything else?

**Review by ekluzek — APPROVED** [review]

**Comment by slevis-lmwg** [comment]
@samsrabin or @ekluzek 
I thought I'd be able to "rebase" this PR at the top where it says "...wants to merge 1 commit into..." but now I do not see such an option. I got myself in this bind by returning to my original `merge-b4bdev-20240321` branch instead of creating a new one from b4b-dev. Do either of you have suggestions for moving forward from here OR should I go back to step 15a?

**Comment by ekluzek** [comment]
Hey @slevis-lmwg. I went ahead and changed it. But I also have had troubling finding it in the past. I've done it enough now that I know what to do. Just an example of it's easier to show someone. So next time we have a meeting I'll show you...

**Comment by samsrabin** [comment]
@slevis-lmwg The reason we specify merging the master branch back into b4b-dev is to guarantee that b4b-dev is up-to-date with the latest master. But if you've double-checked to make sure that this branch at the latest commit is identical to the latest master, it's all good.

**Pull request merged**
