### PR TITLE
Rework crop_calendars suite and cropMonthOutput

### LINKED ISSUE #2659: Test build failure: SMS_P128x1_Lm25.f10_f10_mg37.IHistClm60BgcCrop.izumi_nag.clm-RxCropCalsAdaptGGCMI
### Brief summary of bug

For some reason this test build fails in my #2593 branch. Other nag tests work fine.

### General bug information

**CTSM version you are using:** Commit aeb41823 on my #2593 branch.

**Does this bug cause significantly incorrect results in the model's science?** No

### Important output or errors that show the problem

```
Panic: /home/samrabin/ctsm_scale-mat-reqs-pr2-ggcmiseas/src/fates/parteh/PRTAllometricCNPMod.F90: Unexpected expr node type 432
Internal Error -- please report this bug
Abort
gmake: *** [PRTAllometricCNPMod.o] Error 3
```

### PR DESCRIPTION
**Pull request by samsrabin**
### Description of changes
- Changes `cropMonthOutput` so that h2 files are actually monthly instead of daily
- Changes a nag test to use debug mode (fixing a build error) and run for shorter (fixing cputime exceedance)
- Reworks `RxCropCals*` testmods to not include `crop` testmod

### Specific notes

**Contributors other than yourself, if any:** None

**CTSM Issues Fixed (include github issue #):**
- Fixes #2659 

**Are answers expected to change (and if so in what way)?** Yes:
- All `cropMonthOutput` tests will now have monthly h2 files instead of daily
- Most 25-month `RxCropCals*` tests are changed to 733 days; one changed to 65 days

**Any User Interface Changes (namelist or namelist defaults changes)?** No

**Does this create a need to change or add documentation? Did you do so?** No

Testing performed, if any:
- [x] Affected tests all tested and behave as expected
- [x] aux_clm passes for all tests except the ones I expect changes in (or are missing baselines)—**waiting** until ready in queue.

### CODE REVIEW

**Comment by samsrabin** [comment]
@ekluzek I ended up finding issues that make it so this can't go onto b4b-dev, as we had decided on #2659.

**Comment by wwieder** [comment]
@slevis-lmwg can you review this PR?

**Review by slevis-lmwg — APPROVED** [review]
@samsrabin @wwieder this looks good to me.

**Comment by samsrabin** [comment]
Great, thanks!

**Pull request merged**
