### PR TITLE
Script for modifying neon surface dataset -- updated

### PR DESCRIPTION
**Pull request by negin513**
### Description of changes
This PR includes the following changes to the script for updating the surface dataset at neon sites using available neon data (i.e. `modify_singlept_site_neon.py`) to address ctsm/issues #1353, #1429, and [neon/issue #44](https://github.com/NEONScience/NCAR-NEON/issues/44): 

* Update Organic calculation to use the following equation based on discussions in https://github.com/ESCOMP/CTSM/pull/1375/files#r669590971 : 
ORGANIC = estimatedOC * bulkDensity / 0.58 

* Because estimatedOC is rounded to the nearest integer in neon data, it is sometimes bigger than carbonTot. Therefore, in cases where estimatedOC > carbonTot, we use carbonTot instead of estimatedOC in the above equation. 

* Previously, we had missing data on neon files for some neon soil layers (see https://github.com/ESCOMP/CTSM/issues/1429#issuecomment-881427337). Therefore, it caused some missing values in the updated dataset. Here, we interpolate to fill in the missing data using different interpolation techniques. Finally, we chose to use  linear interpolation to fill in missing data. 

### Specific notes

Contributors other than yourself, if any: @wwieder , @danicalombardozzi

CTSM Issues Fixed (include github issue #): ctsm/issues #1353, #1429, and [neon/issue #44](https://github.com/NEONScience/NCAR-NEON/issues/44

Are answers expected to change (and if so in what way)? N/A 

Any User Interface Changes (namelist or namelist defaults changes)? N/A

Testing performed, if any:
We plotted the soil profiles comparing the original (subset from global), modified (old equation), and modified (new organic equation and linear interpolation filling in the data. 

Here are the results for a few of the sites:
HARV_sf_profile_v6_oc
MOAB_sf_profile_v6_oc
DEJU_sf_profile_v6_oc

In the plots above:

- Blue lines show original values (subset from global dataset).
- Red lines show the previous version of updated values which had missing data and used the old organic equation. i.e.  organic = carbon_tot * bulk_den * 0.1 / layer_depth * 100 / 0.58

- Green dashed lines show the updated values using the new organic equation and filled with linear interpolation. ORGANIC = carbonTot * bulkDensity / 0.58 

- Orange dashed lines similar to the green lines but  the updated organic values using the `estimatedOC` (instead of `carbonTot`) : ORGANIC = estimatedOC * bulkDensity / 0.58 

--------------------

- The new organic equation (green and orange lines) resolves the issue of very big organic at the top layers (especially for forest sites), for example check plots of HARV,  ORNL , BLAN, and DEJU. 
-  The new organic equation also resolves the sudden big organic values at mid layers for example check MLBS
- The results look much better when removing inorganic carbon (using estimated_OC a.k.a. orange lines) and it resolved the issue with the high organic values at deep layers. For example please check MOAB, JORN, CPER, and WOOD.

The results for all sites are in the following folder:
https://drive.google.com/drive/folders/1nuuVRtmISa-lnMHsZ1KrfQp4K3PB7uEa

### CODE REVIEW

**Comment by wwieder** [comment]
@negin513 is this linked with #1539?  If so, should these two PRs be merged with #1467 on @jedwards4b's branch we're using for CTSM-Lab?

**Comment by ekluzek** [comment]
@wwieder just so you know @negin513 and I went over this earlier today as well as #1539 and got them ready to go into #1467 Jim's branch. So I'll be doing that merge shortly.

**Review by ekluzek — APPROVED** [review]
OK, I went through the changes they look fine to me. 

Some of it was a challenge because I think some of them are just formatting changes from running in black. I love having a formatting standard that we can validate against, so I'm very happy about that part.

Functional changes are describes where missing values are handled and the interpolation for organic is handled differently. I'm just assuming that's correct, but @negin513 also provides plots so that's obviously been approved and validated.

So awesome! Thanks so much.

**Comment by wwieder** [comment]
Thanks for the update and good work, Negin.

**Pull request merged**
