### PR TITLE
Merge ctsm5.1.dev020 tag into fates_main_api

### PR DESCRIPTION
**Pull request by glemieux**
### Description of changes

This PR brings the fates_main_api branch up to date with [ctsm5.1.dev020](https://github.com/ESCOMP/CTSM/releases/tag/ctsm5.1.dev020) tag in preparation for merging fates_main_api into ctsm master.

### Specific notes

The only major change that came up during the merge was the need to add `CNFireArea`, `CNFireReadParams`, and `CNFireFluxes` as empty functions to FatesFireBase.F90.  This was necessary due to the refactor that took place in #1155 with https://github.com/ESCOMP/ctsm/commit/e345c390332e8178a0fb814305abc3a656273f4e.

Contributors other than yourself, if any: @ekluzek 

CTSM Issues Fixed (include github issue #): None

Are answers expected to change (and if so in what way)? Only fates-related answers

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
- `aux_clm` suite: `/glade/u/home/glemieux/scratch/tests_0115-165815ch`
- `fates` suite: 
```/glade/u/home/glemieux/scratch/clmed-tests/fma-merge-ctsm5.1.dev020.fates-sci.1.43.2_api.14.2.0-ctsm5.1.dev020-Ce09dc512-F5534a940```

### CODE REVIEW

**Comment by glemieux** [comment]
All non-fates testmods for the `aux_clm` test suite came back b4b.  The fates testmods in this suite ran successfully but are answer changing, which is not unexpected.

I need to manually run `cprnc` for the `fates` suite comparison since the automatic comparison failed due to the change in the compset names from https://github.com/ESCOMP/ctsm/commit/8c6bfdc221603ceb054fc0c2aab6dbeb8890e2f3.  All tests ran successfully.

**Comment by glemieux** [comment]
I should note that upon reviewing the DIFFs for the Fates testmods in the `aux_clm` suite, the original DIFFs were due to the fact that [this update](https://github.com/ESMCI/cime/pull/3663) hasn't been merged into `cprnc` on cheyenne yet.  I built script to run `cprnc` to create the appropriate output with an updated version of `cprnc`.  The files can be found at `/glade/u/home/glemieux/scratch/clmed-tests/fma-merge-ctsm5.1.dev020-aux_clm-fates`

**Comment by glemieux** [comment]
Manual run of `cprnc` for the `fates` regression test suite is complete.  The following testmods are all b4b:
- All `1x1brazil` tests
- `FatesSizeAgeMort`
- `FatesNoFire`
- `FatesST3`

All other tests result in DIFFs.  I believe the likely cause, reviewing the ctsm changelog, is due to the changes to the btran calcuation for fire made in #1155, specifically https://github.com/ESCOMP/CTSM/commit/ec8d075d57c071436921e9599d0e300319e123fe and https://github.com/ESCOMP/CTSM/commit/b1cf8b9f915c328b161f69525c56a04955c5d642.  

@rgknox I ran a 10 year`f45`  grid with for both fates_main_api and this PR branch and compared them here to get a better sense of the location of the changes.  They appear to be relatively sparse and mostly impacting fire related variables, which I think supports my hypothesis about the answer changes.  The notebook can be found here: https://glemieux.github.io/fates-jupyter/fates_main_api/fates_main_api-merges/ctsm5_1_dev020-f45.html

Raw test results can be found here: 
```
/glade/u/home/glemieux/scratch/clmed-tests/fma-merge-ctsm5.1.dev020.fates-sci.1.43.2_api.14.2.0-ctsm5.1.dev020-Ce09dc512-F5534a940
```

**Comment by glemieux** [comment]
After reviewing the `f45` gridded run some more, I noticed that the effective fuel moisture variables were different at the very start of the simulation.  I reviewed the changelog and ran some additional quick (1 year) `f45` cases (creating new branches off fates_main_api and merging in said tags) to see if I could pin point which dev tag may have contributed to this change.  I appears that https://github.com/ESCOMP/CTSM/releases/tag/ctsm5.1.dev002 accounts for the all of the difference at the start of the simulation.  The results can be found in my jupyter notebook: https://github.com/glemieux/fates-jupyter/blob/main/fates_main_api/fates_main_api-merges/ctsm5_1_dev020-f45-start_diff.ipynb.

**Review by ekluzek — APPROVED** [review]
It's hard to review these merge updates. But, it appears to be correct as far as I can see. Possibly the best check might be to compare this to the baseline version, and then compare that to the differences on the fates_main_api branch to it's baseline.

**Comment by glemieux** [comment]
@ekluzek I'm reasonably confident that I've nailed down the source of the differences.  Given this and that the ctsm-side `aux_clm` tests were all b4b, I think we can go ahead and merge this into fates_main_api @rgknox.

**Pull request merged**
