### PR TITLE
Adding fcansno to FATES interface

### PR DESCRIPTION
**Pull request by rosiealice**
### Description of changes
Adds changes to push **fcansno** into the FATES interface to allow snow occlusion of vegetation. This is to facilitate the changes in https://github.com/NGEET/fates/pull/750

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?
Not by itself, no.

Any User Interface Changes (namelist or namelist defaults changes)?

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

Tested in FATES-SP mode.  

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by glemieux** [comment]
All expected tests pass b4b against `ctsm5.1.dev061`: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr750-aux_clm`

**Review by ekluzek — CHANGES_REQUESTED** [review]
As we talked about, I'd just say to line up the whitespace change.

**Comment by glemieux** [comment]
@ekluzek it looks like the failures I was seeing in the final testing is due to some left-over `hobart` category tests having been converted to `izumi` in ctsm5.1.dev062.  Three of those are `fates` non-debug tests and were failing (as expected).  Since they overlap with existing `fates` and `aux_clm` tests and we have this expected failure already covered, I decided to strike the nag version of these tests.

Otherwise, everything ran b4b in `aux_clm` against ctsm5.1.dev062 (except the fates DIFFs as expected), with the exception of a RUN timeout with `ERP_Ld5.f19_g17.I2000Clm50SpRtmFl.izumi_gnu.clm-default`.  It's also the only test with an `NLCOMP` diff.  Here's what they look like: 

```
DRIVER_attributes->PELAYOUT_attributes:
 - atm_ntasks : 96
 + atm_ntasks : 48
DRIVER_attributes->PELAYOUT_attributes:
 - cpl_ntasks : 96
 + cpl_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - cpl_rootpe : 0
 + cpl_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - glc_ntasks : 96
 + glc_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - glc_rootpe : 0
 + glc_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - ice_ntasks : 96
 + ice_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - ice_rootpe : 0
 + ice_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - lnd_ntasks : 96
 + lnd_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - lnd_rootpe : 0
 + lnd_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - ocn_ntasks : 96
 + ocn_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - ocn_rootpe : 0
 + ocn_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - rof_ntasks : 96
 + rof_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - rof_rootpe : 0
 + rof_rootpe : 48
DRIVER_attributes->PELAYOUT_attributes:
 - wav_ntasks : 96
 + wav_ntasks : 528
DRIVER_attributes->PELAYOUT_attributes:
 - wav_rootpe : 0
 + wav_rootpe : 48
```

**Comment by ekluzek** [comment]
OK, so this is showing that the PE layout changed which is odd, because it's obvious that you haven't done anything to change it. Let me rerun the baseline and make sure I didn't mess it up.

**Comment by ekluzek** [comment]
OK, I recognize what happened with the ERP test you refer to above. I changed the PE layout, but must have not rerun the baseline. So I'll remove the old baseline and rerun it on izumi. As well as doing the other tests.

**Comment by glemieux** [comment]
Per a conversation with @ekluzek via chat, we decided to remove high resolution `fates` category tests on izumi since the tests take much longer to run on izumi and we have coverage for these resolutions in `aux_clm` and the `fates` category on cheyenne.

**Comment by glemieux** [comment]
Per conversation with @ekluzek and @billsacks I've moved the `ERP_Ld5.f19_g17.I2000Clm50SpRtmFl.izumi_gnu.clm-default` test from izumi to cheyenne so that we retain coverage for this test configuration at this grid resolution.  The test baseline has been added to the existing `ctsm5.1.dev063` baseline.  The test ran without issue: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_1123-100326ch`

**Review by ekluzek — APPROVED** [review]

**Pull request merged**
