### PR TITLE
Remove manage externals

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes

Removes the manage_externals download mechanism and replaces with git submodules.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? Yes

Users now run ./install instead of ./manage_externals/checkout_externals to get the code. 

Testing performed, if any: currently just basic testing

Important changes that need to happen with this:

- [ ] Update run_sys_tests to work without manage_externals
- [ ] Update README files that mention manage_externals
- [ ] Update users guide documentation (this will likely be done later)...

### CODE REVIEW

**Comment by samsrabin** [comment]
Thanks, Jim! It'll be nice to have this modernized! In my testing, it seems speedier, too. Unfortunately I get an error at the CISM step:

```
Submodule 'components/cism' (https://github.com/jedwards4b/cism) registered for path 'components/cism'
Cloning into '/Users/sam/Downloads/ctsm/components/cism'...
fatal: remote error: upload-pack: not our ref 88947a51ac7c50ecf114384d8a7221950cb86b71
fatal: Fetched in submodule path 'components/cism', but it did not contain 88947a51ac7c50ecf114384d8a7221950cb86b71. Direct fetching of that commit failed.
```

Is it supposed to point to the URL https://github.com/ESCOMP/CISM-wrapper instead of https://github.com/jedwards4b/cism?

I've submitted some minor suggestions in the PR jedwards4b/ctsm#1. Another one that I was unsure about: When I was testing, sometimes when I ran `./install` I'd have to repeatedly enter my Github username and password. I think this would be avoided by specifying, in `.gitmodules`, URLs for the SSH method (`git@github.com:` …) instead of HTTPS (`https://github.com/` …).

Thanks again for your work on this!

**Comment by jedwards4b** [comment]
@samsrabin Thank you so much for giving it a go.  I've corrected the problems you pointed out, please give it another try.

**Comment by samsrabin** [comment]
Thanks, that fixed the checkout.

I had a closer look, and some versions are changed relative to the latest dev tag (ctsm5.1.dev159):
- cime: `0a9126ed` → `94831632`
- cime/CIME/non_py/cprnc: `0a9126ed` → `5e2ca5bb`
- components/cism: `bd194b1f` → `00f5a111`

I checked by comparing the output of the following script at the top level of the repos:
```bash
#!/bin/bash

for d in src/fates cime cime/CIME/non_py/cprnc components/rtm components/mosart components/mizuRoute ccs_config components/cmeps components/cdeps components/cpl7 share libraries/mct libraries/parallelio doc/doc-builder components/cism; do
     if [[ ! -d $d ]]; then
          echo "$d: missing"
          continue
     fi
     pushd $d 1>/dev/null
     echo "$d: $(git rev-parse HEAD)"
     popd 1>/dev/null
done

exit 0
```

Also, even with the internal flag on the CISM install, the following extra directories are installed: ccs_config, cime, components, and share.

**Comment by jedwards4b** [comment]
I think that you'll find that the extra directories are present but empty - not sure if I can fix that.

**Comment by jedwards4b** [comment]
The versions are changed so that I don't need to create separate branches for each component.   I did do this for FMS_interface - but I don't want to create more PR's unless I really need to.

**Comment by samsrabin** [comment]
Ah yes, those directories are empty (or contain only empty directories). That's probably fine.

Makes sense about those version changes, I see now.

I will shortly push a commit to [my PR](https://github.com/jedwards4b/ctsm/pull/1) that adds proper argument handling, which should make it easier to extend `./install` in the future if needed.

**Comment by samsrabin** [comment]
Thanks for handling that! But there's a typo in `install` at line 43: `internale_only`

**Comment by ekluzek** [comment]
@rgknox @glemieux and @adrifoster this will change how FATES people deal with the FATES external in CTSM. So we'd like to hear your perspective. This means FATES will be managed with git submodule rather than an explicit checkout or manage_externals. I think this might make it more similar to how FATES is handled in ELM though? And maybe that's a good thing?

**Comment by rgknox** [comment]
@ekluzek , as you say, fates does interact with E3SM via submodule, so we are used to that system too. So I have no issues with the switch.

**Comment by jedwards4b** [comment]
@wwieder This may take a while yet - I collected a number of requirements from the various stakeholders and have been working on code to address the issues raised.  I will present my progress in Tuesday's cseg meeting and get further feedback.   I will develop component agnostic documentation for the new workflow and hopefully all of the component documentation can just point to that with little or no component specific additions.

**Comment by ekluzek** [comment]
Doing a "git grep manage_externals" I see that there is some documentation that needs to be updated with the change. Most importantly we'll need to change manage_externals to do something different here.

``` text
README:manage_externals -- Script to manage the external source directories
README_EXTERNALS.rst:#. Run the script **manage_externals/checkout_externals**. ::
README_EXTERNALS.rst:      ./manage_externals/checkout_externals
README_EXTERNALS.rst:  ./manage_externals/checkout_externals --help
README_EXTERNALS.rst:  ./manage_externals/checkout_externals
README_EXTERNALS.rst:     ./manage_externals/checkout_externals
README_EXTERNALS.rst:To point to a branch, use ``branch = ...``. Pointing to a branch means that, each time you run ``manage_externals/checkout_externals`` you will get the current latest version of that branch. This can be convenient for in-progress development work, but should not be used when you need a stable version for scientific simulations. There are a number of gotchas with this workflow, so in general you should default to pointing to fixed hashes. (For CTSM master, we require a fixed hash or, usually, a tag.)
doc/ChangeLog:    Update manage_externals (direct push to main-dev)
doc/README.CHECKLIST.master_tags:   2c -- run './manage_externals/checkout_externals -S' to make sure all externals are
doc/README.CHECKLIST.master_tags:         the first column, run ./manage_externals/checkout_externals to update them.)
doc/build_docs:    echo "Obtain doc-builder by running ./manage_externals/checkout_externals -o from the top-level"
doc/design/python_script_user_interface.rst:The distinction between when to use print and when to use logging can admittedly be a bit subjective, as it comes down to the question of whether the given output is part of the fundamental operation of the script – i.e., part of what the script is designed to do is to give this output. For example, ``run_sys_tests`` prints a variety of information when it starts, particularly concerning the git and manage_externals status of the current repository. The rationale for using ``print`` statements for this is that we designed ``run_sys_tests`` to replace some of the repetitive items that we did whenever running the system tests. One of these items was running ``git status`` and ``./manage_externals/checkout_externals -S -v`` to check that the repository is in a clean state. Thus, in this case, our view is that the output from these commands is part of the fundamental purpose of ``run_sys_tests``: it is something we always want to see, and we feel that it is important for anyone running the system tests to review, and thus ``print`` statements are appropriate here.
doc/source/lilac/obtaining-building-and-running/obtaining-and-building-ctsm.rst:  ./manage_externals/checkout_externals
doc/source/lilac/obtaining-building-and-running/obtaining-and-building-ctsm.rst:  ./manage_externals/checkout_externals
doc/source/lilac/obtaining-building-and-running/obtaining-and-building-ctsm.rst:**be sure to rerun** ``./manage_externals/checkout_externals`` **after doing so.**
doc/source/lilac/specific-atm-models/wrf.rst:    ./manage_externals/checkout_externals
python/ctsm/run_sys_tests.py:    skip_git_status (bool): if True, skip printing git and manage_externals status
python/ctsm/run_sys_tests.py:        help="Skip printing git and manage_externals status,\n"
python/ctsm/run_sys_tests.py:        "or if git or manage_externals are currently broken in your sandbox.\n",
python/ctsm/run_sys_tests.py:    manic = os.path.join("manage_externals", "checkout_externals")
python/ctsm/run_sys_tests.py:    manage_externals_status = subprocess.check_output(
python/ctsm/run_sys_tests.py:    output += 72 * "-" + "\n" + "manage_externals status:" + "\n"
python/ctsm/run_sys_tests.py:    output += manage_externals_status
```

**Comment by ekluzek** [comment]
This is an important change for CESM3 so we all should look into this more and do testing on it.

**Comment by wwieder** [comment]
@jedwards4b we've been asked to take this out for a test drive, but I have no idea where to begin.  Can you hold my hand by posting instructions about how I can try out this new workflow?  It will help me then explain the rollout to the LMWG community.

**Comment by jedwards4b** [comment]
Here are instructions for CTSM, be aware that these instructions are still evolving and may be subject to further change.
```
git clone https://github.com/jedwards4b/CTSM -b remove_manage_externals CTSM_RME
cd CTSM_RME
./bin/git-fleximod checkout

```
At this point you will have a complete ctsm checkout.
To check the status
`./bin/git-fleximod status`
To update to a new external tag, edit .gitmodules and change the fxtag for any component and then run
`./bin/git-fleximod update`

use `./gin/git-fleximod -h  ` for a list of options.  
Let me know if you have any questions.

**Comment by wwieder** [comment]
I think this worked as intended, but could some kind of print statement saying something like _"externals successfully updated"_ be added?  Currently I only get the following, which makes me wonder if anything happened or I have an error?

```
[/glade/derecho/scratch/wwieder/CTSM_RME] (remove_manage_externals=)
$./bin/git-fleximod update
-bash: ./bin/git-fleximod: No such file or directory
```

**Comment by jedwards4b** [comment]
No - it didn't get the tool, hang on.

**Comment by jedwards4b** [comment]
I'm sorry - I gave you the wrong branch name
```
cd  /glade/derecho/scratch/wwieder/CTSM_RME
git checkout branches/CESM3_dev.n04_ctsm5.1.dev145_rme
```
then try again.

**Comment by wwieder** [comment]
Thanks @jedwards4b. 

OK, now I actually have a bin directory and get the print updates for each external.  Love it, but still getting the following error:

```
Successfully checked out ccs_config
Recursively checking out submodules of cime /glade/derecho/scratch/wwieder/CTSM_RME/cime https://github.com/jedwards4b/cime
Traceback (most recent call last):
  File "./bin/git-fleximod", line 435, in <module>
    sys.exit(_main_func())
  File "./bin/git-fleximod", line 425, in _main_func
    submodules_checkout(gitmodules, root_dir, fxrequired)
  File "./bin/git-fleximod", line 367, in submodules_checkout
    submodule_checkout(root_dir, name, path, url=url, tag=fxtag)
  File "./bin/git-fleximod", line 245, in submodule_checkout
    submodules_checkout(gitmodules, repodir, ["I:T"])
  File "./bin/git-fleximod", line 367, in submodules_checkout
    submodule_checkout(root_dir, name, path, url=url, tag=fxtag)
  File "./bin/git-fleximod", line 234, in submodule_checkout
    git.git_operation("clone", "-b", tag, url, path)
  File "./bin/../lib/python/site-packages/fleximod/gitinterface.py", line 45, in git_operation
    return utils.execute_subprocess(command, output_to_caller=True)
  File "./bin/../lib/python/site-packages/fleximod/utils.py", line 275, in execute_subprocess
    commands_str = " ".join(commands)
TypeError: sequence item 5: expected str instance, NoneType found
```

A few other comments

- **Can the command be more intuitively named?**  This comment is largely semantic. FWIW I like the names associated with manage_externals and checkout_externals, as it's more intuitive what's going on (even if I don't understand the details).  Calling git-fleximod from the bin directory doesn't make sense (to a scientist with zero formal SE training). I appreciate this may be more meaningful on the SE side (note commands like checkout, status, and update all make sense)
- **Documentation:** Specifically, `README_EXTERNALS.rst` should be removed and replaced with something similar to get users started with using this new tool.  We can also work on updating our wiki and tutorials, but that can be done outside of this PR.

**Comment by wwieder** [comment]
Looks like the following submodules failed (maybe this is intended):
```
Submodule cime at tag cime6.0.198_rme01
Submodule share not checked out, aligned at tag share1.0.17
Submodule mct not checked out, aligned at tag MCT_2.11.0
Submodule parallelio not checked out, aligned at tag pio2_6_2
Submodule doc-builder not checked out, aligned at tag v1.0.8
Submodule cism not checked out, aligned at tag cismwrap_2_1_96_rme02
```

one the naming side. what if the commands was something like ./bin/git-submodules

**Comment by jedwards4b** [comment]
git-submodules is an official git tool, they probably wouldn't like us repurposing that name.   I'm about to push an update of the tool, it will include a fix for that issue.

**Comment by wwieder** [comment]
OK, happy to test again when you're ready.

what about manage-submodules for a name?   You made the tool, and ultimately should name it, I'm just trying to suggest potentially user friendly alternatives.

**Comment by jedwards4b** [comment]
There really is a purpose to the git- prefix.   If this tool is in your path you can run it like any other git command: git fleximod (without the hyphen).   I'm open to changing the fleximod part but I also think that users will quickly accept the name as long as it isn't too lengthy.

**Comment by mvertens** [comment]
@jedwards4b - I think that having the git- prefix is very confusing since this is not a git command. Just because you can run it 'like' a git command does not make it a git command and for users that have a lot of expertise in git this will just lead to erroneous expectations. In addition, I think that a more intuitive name (several have been suggested that I feel are all more intuitive then fleximod) would be a good idea.

**Comment by jedwards4b** [comment]
Please consider the following article.  I fully believe this to be a git command
it is totally general and not tied to escomp models in any way.
https://gitbetter.substack.com/p/automate-repetitive-tasks-with-custom

**Comment by mvertens** [comment]
@jedwards4b - thanks for pointing out this article.

**Comment by wwieder** [comment]
One more comment, maybe we can just remove the `README_EXTERNALS.rst` all together?  @ekluzek and @slevis-lmwg do you think the information from `./bin/git-fleximod -h` enough for users to know how to use this tool?  Maybe the help command can just be flushed out a bit more, especially with instructions for how to select a particular set of exernals (if needed)?

**Comment by jedwards4b** [comment]
@wwieder I have updated ctsm branch  branches/CESM3_dev.n04_ctsm5.1.dev145_rme 
with a new version of git-fleximod, please give it a try.

**Comment by glemieux** [comment]
I just gave this a try and it looks like its working:

```
09:16 $ ./bin/git-fleximod update
e                cdeps not checked out, aligned at tag cdeps1.0.26_rme01
e                cmeps not checked out, aligned at tag cmeps0.14.49
e                fates not checked out, aligned at tag sci.1.67.2_api.27.0.0
e                  rtm not checked out, aligned at tag rtm1_0_78
e               mosart not checked out, aligned at tag mosart1_0_48
e            mizuRoute not checked out, aligned at tag cesm-coupling.n02_v2.1.2_rme02
e           ccs_config not checked out, aligned at tag ccs_config_cesm0.0.84
e                 cime not checked out, aligned at tag cime6.0.198_rme05
e                share not checked out, aligned at tag share1.0.17
e                  mct not checked out, aligned at tag MCT_2.11.0
e           parallelio not checked out, aligned at tag pio2_6_2
e          doc-builder not checked out, aligned at tag v1.0.8
e                 cism not checked out, aligned at tag cismwrap_2_1_96_rme02
```

**Comment by samsrabin** [comment]
@jedwards4b Could you update this to your latest version so we can start testing with it?

**Comment by jedwards4b** [comment]
I have an update here: 
To github.com:jedwards4b/ctsm.git
   979c1255c..9d85e815a  rme/ctsm5.1.dev175 -> rme/ctsm5.1.dev175

I think that I need to close this PR and open a new one.

**Pull request closed without merging**
