### PR TITLE
Subset mesh files for regional cases and add user-mods for regional cases. 

### PR DESCRIPTION
**Pull request by negin513**
### Specific notes
This PR adds capability to subset mesh files for a regional case based on the region of choice. 

Contributors other than yourself, if any: @swensosc and @adrifoster

CTSM Issues Fixed (include github issue #): #1513 

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No, option `--subset-mesh` is added to `subset_data`. 

Testing performed, if any:
Plotting the mesh files to make sure the extracted mesh file makes sense.

### CODE REVIEW

**Comment by jkshuman** [comment]
@negin513 this appears to subset the files appropriately when I view them. 
I am trying to run a regional case and running into problems. I have been trying out a few things, but we should set up a time to meet.

**Comment by jkshuman** [comment]
@negin513 comments on using the script:
Is there help? I wasn't able to access it when I tried ./subset_data -help or ./subset_data --help
I like the progress bar. Would be great to add a print statement that identifies the datasets being subset.
I got this message, but it still seemed to create the regional subset:

> /glade/work/jkshuman/sfcdata/subset_mesh/ctsm/tools/site_and_regional/../../python/ctsm/site_and_regional/regional_case.py:460: SerializationWarning: saving variable elementMask with floating point data as an integer dtype without any _FillValue to use for NaNs
>   f_out.to_netcdf(mesh_out)

I did not see a way to specify the directory where these files would go. It took me a bit to figure out where they were located.

**Comment by jkshuman** [comment]
@negin513 after fixing what seemed to be a typo I got it to build and submit, but then had a fail with this error in the cesm.log:

> 10:MPT ERROR: Rank 10(g:10) is aborting with error code 1.
10:	Process ID: 61846, Host: r2i0n25, Program: /glade/scratch/jkshuman/test9_mesh_user-mods_SAmer_0.9x1.25_b8c91151_e54a4947/bld/cesm.exe
10:	MPT Version: HPE MPT 2.22  03/31/20 15:59:10
10:
10:MPT: --------stack traceback-------
-1:MPT ERROR: MPI_COMM_WORLD rank 7 has terminated without calling MPI_Finalize()
-1:	aborting job

**Comment by negin513** [comment]
@jkshuman Thanks for your comments. 
> @negin513 comments on using the script: Is there help? I wasn't able to access it when I tried ./subset_data -help or ./subset_data --help I like the progress bar. 

You can see the subset_data help options using the following:

```
./subset_data --help 
or 
./subset_data -h
```

You can see specify to see options only specific to region or single point:

Show only regional option:
```
./subset_data region -h
or 
./subset_data region --help
```

Show only single point options:
```
./subset_data point -h
or 
./subset_data point --help
```

**Comment by jkshuman** [comment]
@negin513 thanks. the help wasn't working yesterday, but perhaps I have the wrong conda environment. it is working today when I update my conda environment.

for the help description on the regional lat and lon can you include the directions, as in NE corner etc?

**Comment by negin513** [comment]
> Would be great to add a print statement that identifies the datasets being subset. 


Thank Jackie. The additional messages will be printed out using  `--debug` or `-v` and `--verbose`. The interface is similar to `./subset_data point`. I am in favor of adding those as print statements but the SE team decided to refrain from any print statements from python code in #1461. 

> I got this message, but it still seemed to create the regional subset:
> 
> > /glade/work/jkshuman/sfcdata/subset_mesh/ctsm/tools/site_and_regional/../../python/ctsm/site_and_regional/regional_case.py:460: SerializationWarning: saving variable elementMask with floating point data as an integer dtype without any _FillValue to use for NaNs
> > f_out.to_netcdf(mesh_out)
> 

This is an xarray warning but I will change this to ignore this message.

**Comment by negin513** [comment]
> @negin513 comments on using the script: Is there help? I wasn't able to access it when I tried ./subset_data -help or ./subset_data --help I like the progress bar. Would be great to add a print statement that identifies the datasets being subset. I got this message, but it still seemed to create the regional subset:
> 
> > /glade/work/jkshuman/sfcdata/subset_mesh/ctsm/tools/site_and_regional/../../python/ctsm/site_and_regional/regional_case.py:460: SerializationWarning: saving variable elementMask with floating point data as an integer dtype without any _FillValue to use for NaNs
> > f_out.to_netcdf(mesh_out)
> 
> I did not see a way to specify the directory where these files would go. It took me a bit to figure out where they were located.

The interface is similar to single point subsetting. So by default it create a folder called `subset_data_regional` in the directory where you are running this from. For single point it does the same thing with `subset_data_single_point` directory. 

You can specify the output directory using command line argument `--outdir`. 
For example the following will create a directory called this_region where you are running the code from. 
```
./subset_data region --create-surface --create-mesh --outdir this_region
```

**Comment by jkshuman** [comment]
@negin513 I updated the comment about the help failure to include the error associated with python.

**Comment by negin513** [comment]
> @negin513 thanks. the help wasn't working yesterday, but it seems to be a python error. If I update my python environment it works.

> for the help description on the regional lat and lon can you include the directions, as in NE corner etc? (rather than start and end)

Good idea.I will change the help message to show westernmost/easternmost language instead of start and end.

**Comment by jkshuman** [comment]
path to the latest case: /glade/work/jkshuman/FATES_cases/test/test9_mesh_user-mods_SAmer_0.9x1.25_b8c91151_e54a4947

**Comment by wwieder** [comment]
@negin513 do you local changes to this PR that you can push so we can work on bringing this into main?

**Comment by negin513** [comment]
Thanks for your message. I would like to give a quick presentation at this CTSM SE meeting (Nov 3 2022) about how this works and what additional capabilities it has. 
This includes solutions for creating mesh files for WRF-CTSM runs and can be used with any netcdf files with 1d or 2d lat and lon coordinates.

**Comment by chrystali2002** [comment]
> I would like to give a quick presentation at this CTSM SE meeting (Nov 3 2022) about how this works and what additional capabilities it has. This includes solutions for creating mesh files for WRF-CTSM runs and can be used with any netcdf files with 1d or 2d lat and lon coordinates.

Looking forward to the presentation

**Comment by ekluzek** [comment]
@chrystali2002 here are the joining details for the meeting. This will be 9:30am MDT and you can join on google meet, or in the 315 conference room at the Mesa Lab.

https://meet.google.com/pkq-ghfn-gpv

all of the conferencing info. is here...

```
CTSM Software Engineering Team
Thursday, November 3 · 9:30 – 11:00am
Google Meet joining info
Video call link: https://meet.google.com/pkq-ghfn-gpv
Or dial: ‪(US) +1 563-538-1719‬ PIN: ‪417 402 863‬#
More phone numbers: https://tel.meet/pkq-ghfn-gpv?pin=9595653316138
```

**Comment by ekluzek** [comment]
This is replaced by #1892

**Comment by ekluzek** [comment]
The user-mods part of this already came in. So I'm closing this one.

**Pull request closed without merging**
