### PR TITLE
Fix the FUN bug, where an if statement was backwards...

### LINKED ISSUE #704: FUN code logic to reduce or increase carbon allocation used for uptake is reversed
### Brief summary of bug

This bug was first reported in Nov 2018 and subsequently investigated but an issue has not been filed until this point.
Carbon allocation to uptake responds to CN(uptake-cost) and CN(actual).  The intended implementation is: For C:N less than the target C:N, C allocation is reduced with cost. For C:N greater than the target C:N, C allocation is increased with high C:N.  However, the actual implementation is reversed.

### General bug information

**CTSM version you are using:** release-clm5.0.01

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** All with FUN on

### Details of bug

FUNbugCodeDiff

### Important output or errors that show the problem

We've completed 40 year global 1850 runs (after AD and post-AD spinup) for a control and with the bug fix.  Diagnostics are here:

http://webext.cgd.ucar.edu/I1850/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_1850/lnd/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_1850.21_40-clm50_release-clm5.0.15_2deg_GSWP3V1_1850.21_40/setsIndex.html

We've also completed a historical run.  Diagnostics are here:

http://webext.cgd.ucar.edu/I20TR/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_hist/lnd/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_hist.1995_2014-clm50_release-clm5.0.15_2deg_GSWP3V1_hist.1995_2014/setsIndex.html

Our assessment is that the impact is relatively small, but would affect climate; however it doesn’t appear to strongly affect transient C response.

A branch with this fix is here:

https://github.com/olyson/ctsm/tree/delta_CN_FUNbug

### PR DESCRIPTION
**Pull request by ekluzek**
Apply the difference from the olyson/delta_CN_FUNbug off of release-clm5.0.15 to ctsm/master.

### Description of changes

Technical notes: Page 167

The bug in the FUN model source code is that the functions corresponding
to these two conditions relevant to deltaCN are placed in a wrong order. So
under the deltaCN > 0 condition, it actually uses the function for deltaCN <
0.

``` fortran
1238 if(delta_CN .gt.0.and. frac_ideal_C_use.lt.1.0)then
1239 frac_ideal_C_use = frac_ideal_C_use + (1.0_r8-frac_ideal_C_use)*min(1.0_r8, delta_CN/fun_cn_flex_c(ivt(p)));
1240 end if
1241 ! If we have too much N (e.g. from free N retranslocation) then make frac_ideal_c_use even lower.
1242 ! For a CN delta of fun_cn_flex_c, then we reduce C expendiure to the minimum of 0.5.
1243 ! This seems a little intense?
1244 if(delta_CN.lt.0.0)then
1245 frac_ideal_C_use = frac_ideal_C_use + 0.5_r8*(1.0_r8*delta_CN/fun_cn_flex_c(ivt(p)))
1246 endif
```

Clm5.0/src/biogeochem/CNFUNMod.F90

Original code

``` fortran
1238 if(delta_CN.lt.0.0)then
1239 frac_ideal_C_use = frac_ideal_C_use + (1.0_r8-frac_ideal_C_use)*min(1.0_r8, delta_CN/fun_cn_flex_c(ivt(p)));
1240 end if
1241 ! If we have too much N (e.g. from free N retranslocation) then make frac_ideal_c_use even lower.
1242 ! For a CN delta of fun_cn_flex_c, then we reduce C expendiure to the minimum of 0.5.
1243 ! This seems a little intense?
1244 if(delta_CN .gt.0.and. frac_ideal_C_use.lt.1.0)then
1245 frac_ideal_C_use = frac_ideal_C_use
```

### Specific notes

Contributors other than yourself, if any: @olyson, @rosiealice, Yanyan Cheng, Maoiyi Huang

CTSM Issues Fixed (include github issue #): #704 
 Fixes #704 -- FUN bug

Are answers expected to change (and if so in what way)? yes (when FUN is on, so Clm50Bgc)

Any User Interface Changes (namelist or namelist defaults changes)? None

Testing performed, if any: regular testing being done

We've completed 40 year global 1850 runs (after AD and post-AD spinup) for a control and with the bug fix (on release-clm5.0.15). Diagnostics are here:

http://webext.cgd.ucar.edu/I1850/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_1850/lnd/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_1850.21_40-clm50_release-clm5.0.15_2deg_GSWP3V1_1850.21_40/setsIndex.html

We've also completed a historical run. Diagnostics are here:

http://webext.cgd.ucar.edu/I20TR/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_hist/lnd/clm50_release-clm5.0.15_delta_CN_FUNbug_2deg_GSWP3V1_hist.1995_2014-clm50_release-clm5.0.15_2deg_GSWP3V1_hist.1995_2014/setsIndex.html

Our assessment is that the impact is relatively small, but would affect climate; however it doesn’t appear to strongly affect transient C response.

### CODE REVIEW

**Comment by olyson** [comment]
Looks good to me.

**Comment by ekluzek** [comment]
OK, tests have passed on cheyenne as expected. A test that previously failed inexplicably started working (for #550), so I'm rerunning that one. I have some failures on hobart to sort through.

**Comment by ekluzek** [comment]
Rerunning the test -- it now fails properly as expected.

**Comment by ekluzek** [comment]
OK, I fixed the testing on hobart. Now everything is as expected.

**Pull request merged**
