### PR TITLE
Add excess ice user guide documentation

### LINKED ISSUE #1923: Add documentation on excess ice to the technical note
With #1229 and PR #1787 we need to have excess ice documented in the tech note.

### PR DESCRIPTION
**Pull request by mvdebolskiy**
### Description of changes

Added how to run cases with excess ice turned on to the special cases in user guide

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed:
- Contributes to #2113 
- Resolves #1923

### CODE REVIEW

**Comment by wwieder** [comment]
Thanks for adding this @mvdebolskiy. Do you feel like the PR is ready for review?  If so, does it make sense for @dlawrenncar to review or someone else?

**Comment by mvdebolskiy** [comment]
@wwieder sure, @dlawrenncar can review this.

**Comment by samsrabin** [comment]
I've requested changes in the PR linked by my mention above. @dlawrenncar and @swensosc, you're off the hook :-).

**Review by samsrabin — APPROVED** [review]
Thanks, Matvey!

**Pull request merged**
