### PR TITLE
Remove old code for snw_rds restart that looks no longer needed

### PR DESCRIPTION
**Pull request by billsacks**
It looks like this was there for backwards compatibility, but I can't
imagine it being needed any more. The removed code block was messing
with our ability to cleanly separate WaterStateType for water isotopes.

### CODE REVIEW

**Comment by billsacks** [comment]
@ekluzek - this code block was tripping @mathewvrothstein up in his work to separate WaterStateType. I'm kicking off testing overnight to make sure it's safe to remove this according to the test suite, but please let me know if you can see any reason why it wouldn't be safe to remove this.

Assuming all tests pass, can I go ahead and bring this to master (making a little tag with just this change)? If that's not convenient, I can just give this change to @mathewvrothstein to merge to his branch.

**Comment by ekluzek** [comment]
Since, this isn't required for the release, I'd like to have it stay away from master for a little bit longer. Sounds like that would be OK as well.

**Comment by billsacks** [comment]
Thanks, @ekluzek - I'll have @mathewvrothstein just merge these changes to his branch, then. I'll go ahead and close this PR.

**Comment by billsacks** [comment]
The full test suite passed and was bit-for-bit with clm5.0.dev012, so I think this is a safe change to make.

**Comment by billsacks** [comment]
Actually, I'm going to reopen this and let it auto-close when it comes to master, because I think that will give better traceability.

**Comment by billsacks** [comment]
I have closed this because I reimplemented these changes off of the latest version of master in a separate branch that will come to master soon.

**Pull request closed without merging**
