### PR TITLE
Merge ctsm1.0.dev105 tag into fates_main_api 

### PR DESCRIPTION
**Pull request by glemieux**
### Description of changes
This PR brings the fates_main_api branch up to date with [ctsm1.0.dev105](https://github.com/ESCOMP/CTSM/releases/tag/ctsm1.0.dev105) tag to incorporate fixes to address #1125.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #): #1125 

Are answers expected to change (and if so in what way)? Only fates outputs expected to change relative to ctsm1.0dev.105 tag

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
`aux_clm` suite outputs: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev105-aux_clm`
`fates` suite outputs: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev105-merge`

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by glemieux** [comment]
For the `aux_clm` suite, currently only one test is still PENDing in the Cheyenne queue.  All other tests pass B4B with two FAILs:

- `LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac` fails during MODEL_BUILD
- `SMS.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.ISSP585Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode` fails during RUN.  I think this may be due to hitting the wallclock limit?

For the `fates` suite, all tests passed, although not B4B against the previous baseline generated off of the ctsm1.0.dev095 merge.  This is not unexpected given that there were answer changing updates made during ctsm1.0.dev102 on master.

**Comment by glemieux** [comment]
Looking in the `LILAC` build failure, it looks like the project number isn't being passed from the `run_sys_test` wrapper for some reason.  The build_ctsm.bldlog shows: 
```
ERROR while running:
/glade/u/home/glemieux/ctsm/cime/scripts/create_newcase --output-root /glade/scratch/glemieux/ctsm-tests/tests_ctsmdev105-aux_clm/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac.C.ctsmdev105-aux_clm_int/lilac_build --case /glade/scratch/glemieux/ctsm-tests/tests_ctsmdev105-aux_clm/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac.C.ctsmdev105-aux_clm_int/lilac_build/case --compset I2000Ctsm50NwpSpAsRsGs --res f10_f10_musgs --compiler intel --driver nuopc --run-unsupported --machine cheyenne
...
No project info available
ERROR: PROJECT_REQUIRED is true but no project found
```

**Comment by billsacks** [comment]
The arcticGris test hit the walltime limit. I tell this by looking at the TestStatus file, which shows `RUN time=1222`, and comparing that with:

```
$ ./xmlquery JOB_WALLCLOCK_TIME

Results in group case.st_archive
	JOB_WALLCLOCK_TIME: 00:20:00
```

I wouldn't worry about that test for the sake of testing your integration.

For the LILAC test, I think you uncovered a real issue that I will fix ASAP. (Thank you!) Again, you don't need to worry about that for the sake of the FATES testing.

**Comment by glemieux** [comment]
Thanks @billsacks.  I see that the `ARTICGRIS` wallclock limit is expected for ctsm1.0.dev105 from #1096.  It looks like this was fixed #1079 with ccba4b214274ca744467bbe09bc800b98f8957db, which was included in ctsm1.0.dev106, so I figure we'll catch up to this later and can call this an expected failure for this PR.

**Review by ekluzek — APPROVED** [review]
It's hard to go through these long list of changes. But, it does look like the update to ctsm1.0.dev105. A lot of the changes that come in aren't ones that FATES would care about (new SE, and FV3 grids, and LILAC). But, there are also some important bug fixes that come in ctsm1.0.dev102. The CNFire change was good to bring in as it required some work on the FATES interface side. It was good to get that into FATES.

**Comment by billsacks** [comment]
@glemieux the small diffs in #1146 should fix the LILAC test issue. If you have time and want to redo that one test with those diffs applied, I'd appreciate knowing if it works for you - but no worries if you don't have time to retry that right now.

**Comment by glemieux** [comment]
@billsacks I manually adding in the diff that you pointed to and the MODEL_BUILD get started, but it's failing elsewhere in the build now.  Here's a partial copy from the atm_driver.bldlog:
```
error #7012: The module file cannot be read.  Its format requires a more recent F90 compiler.   [CTSM_LILACCOUPLINGFIELDINDICES]
  use ctsm_LilacCouplingFieldIndices
------^
```
The test case was run via `run_sys_test` using `-t` option to specify the LILAC test.  The log is here: 
```
/glade/scratch/glemieux/ctsm-tests/tests_ctsmdev105-lilac/LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac.C.ctsmdev105-lilac/lilac_atm_driver/bld/atm_driver.bldlog
```

**Comment by billsacks** [comment]
@glemieux sorry for the continued issues. I'm glad you were able to work around this issue. I think I have also fixed it robustly in #1149 . I'll be interested to know if that fix works for you, too... though I suspect it will, since I was able to reproduce your issue by changing my environment to look like yours, and then #1149 got things working for me with your environment.

**Comment by glemieux** [comment]
@billsacks the addition in #1149 did the trick.  I was able to get the LILAC test to pass b4b using my default environment.  Thanks again!

**Comment by glemieux** [comment]
I added in a fix in commit https://github.com/ESCOMP/CTSM/pull/1137/commits/75d2118d99bd8579e41e19a4085397149c27b81e to the testmod definition for FatesHydro to address #1160.

**Comment by glemieux** [comment]
Quick note that the `NLCOMP` DIFF is expected due to an update from ctsm1.0.dev.104 that removes the need to define `dtime` in the user_nl_clm file.

**Comment by glemieux** [comment]
@rgknox the f10 test comparing the fates_main_api baseline and used acre to compare as suggested.  The `TLAI` and `ED_BIOMASS` are bit for bit, which is not unexpected.  Scanning the RMS differences in the output above seems to show that most of the variable differences are with respect to urban and snow related variables.  The plots (and files used to generate the plots) can be found here in my google drive: https://drive.google.com/drive/folders/1N2SXW9V0KCHs8V6E9ENP7cOKBhoDjAF7?usp=sharing

Note I got the `ERS_D_Lm12.1x1_brazil.I2000Clm50FatesCruGs.cheyenne_intel.clm-Fates_nat_and_anthro_ignitions` test to run, but this time it failed in a different manner than expected (recall that it had failed by hitting the wallclock limit prior):
```
/glade/u/home/glemieux/scratch/clmed-tests/ctsmdev105-nutrient_premerge.fates-sci.1.42.0_api.14.0.0-ctsm1.0.dev105-Cb6f63958-F03a17bfe/ERS_D_Lm12.1x1_brazil.I2000Clm50FatesCruGs.cheyenne_intel.clm-Fates_nat_and_anthro_ignitions.C.20200930_224218_6dgabr
```

Weirdly when I ran the test on it's own, it passes the run but fails the exact restart (which is the expected failure):
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev105-nutrients-lightning/ERS_D_Lm12.1x1_brazil.I2000Clm50FatesCruGs.cheyenne_intel.clm-Fates_nat_and_anthro_ignitions.ctsmdev105-nutrients-lightning
```
That said, I think we probably can go ahead and integrate this.  I'll try and address the `anthro` tests failure modes in a different PR.

**Review by rgknox — APPROVED** [review]

**Pull request merged**
