### PR TITLE
Update git-fleximod to v0.8.2

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Same as #2631, but on b4b-dev

### Specific notes

Contributors other than yourself, if any: @jedwards4b 

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Does this create a need to change or add documentation? Did you do so? No

Testing performed, if any: Ran git-fleximod on Derecho and Izumi

### CODE REVIEW

**Comment by ekluzek** [comment]
I see the follow for git fleximod status which looks like errors, but I think it's actually OK:

```
./bin/git-fleximod status
                 fates at tag sci.1.73.0_api.35.0.0
                  cism at tag cismwrap_2_2_001
                     source_cism at tag cism_main_2.01.013
                   rtm at tag rtm1_0_79
                mosart at tag mosart1_0_49
             mizuRoute at tag cesm-coupling.n02_v2.1.2
            ccs_config at tag ccs_config_cesm0.0.106
                  cime at tag cime6.0.246
          e    CIME/non_py/cprnc has no fxtag defined in .gitmodules, module at v1.0.6
s                cmeps wavice 6384ff4e is out of sync with .gitmodules cmeps0.14.63
                 cdeps at tag cdeps1.0.34
                             fox at tag 4.1.2.1
                          genf90 at hash 4816965
                 share at tag share1.0.19
                   mct at tag MCT_2.11.0
            parallelio at tag pio2_6_2
e          doc-builder not checked out, aligned at tag v1.0.8 (optional)
    testfails = 2, local mods = 0, needs updates 11
```

**Comment by ekluzek** [comment]
We'll pause on this to sort out the above error. Likely need to wait until Jim is back...

**Comment by wwieder** [comment]
Is this ready for b4b dev?

**Comment by jedwards4b** [comment]
@will this is way way behind - git-fleximod is in version 0.9.2 - I recommend updating directly to that version.

**Pull request closed without merging**
