### PR TITLE
Change small snocan to zero

### LINKED ISSUE #2041: LWISO_Ld10.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_gnu.clm-coldStart FAIL in ctsm5.2
### Brief summary of bug

This test fails in ctsm5.2
`LWISO_Ld10.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_gnu.clm-coldStart` 
with
`ERROR in CompareBulkToTracer: tracer does not agree with bulk water`

### General bug information

**CTSM version you are using:** [output of `git describe`]
alpha-ctsm5.2.mksrf.16_ctsm5.1.dev123

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
Yes

**Configurations affected:**
See test name above.

### Details of bug

This is the first time that we have tried to run the test suites with ctsm5.2. The failing test uses a new fsurdat in ctsm5.2:
`/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0/surfdata_10x15_hist_78pfts_CMIP6_2000_c230517.nc`
...relative to ctsm5.1:
`/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_10x15_hist_78pfts_CMIP6_simyr2000_c190214.nc`

@billsacks 
@ekluzek suggested that you may have quicker insight into this failure than we would.

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes

#2041 and #2048 discuss and resolve a test failure in the ctsm5.2 branch. The failure goes away when we reset small snocan to zero.

@billsacks recommended merging this change in ctsm5.1 and then updating the ctsm5.2 branch to the latest ctsm5.1.

### Specific notes

Contributors other than yourself, if any:
@billsacks @ekluzek 

CTSM Issues Fixed (include github issue #):
Fixes #2041 #2048 

Are answers expected to change (and if so in what way)?
Yes, more than round off.
Should not change climate.
I will update the Answer-changing tags wikipage as [recommended below](https://github.com/ESCOMP/CTSM/pull/2053#issuecomment-1634112613) and will follow up with a test simulation.

Any User Interface Changes (namelist or namelist defaults changes)?
No.

Testing performed, if any:
The test that was failing in ctsm5.2
`LWISO_Ld10.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_gnu.clm-coldStart`
now passes.

### CODE REVIEW

**Review by billsacks — APPROVED** [review]

**Comment by billsacks** [comment]
Thanks @slevis-lmwg ! I would probably not call this "significant" myself. In fact, I'd probably say that the answer changes from this change are *expected* to be roundoff-level, but then (like many initially-roundoff-level answer changes) grow over time. It's true that the end result is showing answer changes that are perhaps somewhat bigger than I'd expect due to initially roundoff-level answer changes, but fundamentally I would still consider this to be a roundoff-level change, since it just truncates roundoff-level-greater-than-zero states (which probably were intended to be zero) to exactly zero. Reasons this may be greater-than-roundoff-level are (1) if there is some issue with this implementation that you and I aren't seeing; or (2) if there is some significant behavior change that depends on whether snocan is exactly zero vs. non-zero. But I might still argue that (2) doesn't change this from being fundamentally a roundoff-level change.

These thoughts don't really impact the path forward, except for how you document this change. Of course, feel free to document it how you want to, but I raise these points if you wants to stay consistent with how I've classified changes in the past.

**Comment by slevis-lmwg** [comment]
@billsacks thank you, this helps. I do prefer to stay consistent with how you have classified changes before.

**Comment by slevis-lmwg** [comment]
Test-suites:
Izumi `./run_sys_tests -s aux_clm -c ctsm5.1.dev131 -g ctsm5.1.dev136.slevis` IN PROGRESS

**Comment by slevis-lmwg** [comment]
I'm running the test-suites in prep. for the merge.

**Comment by slevis-lmwg** [comment]
Test-suites
Cheyenne: roundoff diffs expected
Izumi: roundoff diffs expected

**Comment by slevis-lmwg** [comment]
Follow-up PR to this one:
#2457

**Pull request merged**
