### PR TITLE
Fates api16.1 (parameter file updates)

### LINKED ISSUE #1383: Change shebang of python to python3 in buildlib /buildnml
This is for compatibility with the latest cime which we are using. But we should change the shebang lines for python programs to use "python3" rather than "python". It needs to be done for buildlib and buildnml (and should also be done for MOSART, RTM and mizuRoute). It could also be done for other python scripts as well.

### PR DESCRIPTION
**Pull request by rgknox**
### Description of changes

This set of changes updates the fates external pointer to API 16.1, which includes an updated parameter file.  The new parameter file includes new fields, no modified fields (ie name or dimension changes) and no removals.  None of the new parameters in the file are yet used (forthcoming FATES side PRs), except for the parameter theta_cj_c3 and theta_cj_c4, which are the quadratic smoothing strengths/stiffnesses between the carboxylation limited and light limited solutions on photosynthesis. Parameter values for the  fates_maintresp_reduction_intercept parameter were modified to fix a typo.

Synchronized with https://github.com/NGEET/fates/pull/759

### Specific notes

Contributors other than yourself, if any: @ckoven @JunyanDing @rosiealice @glemieux @xuchongang

CTSM Issues Fixed (include github issue #):

  Fixes #1383 

Are answers expected to change (and if so in what way)?  Only for FATES

The fates_maintresp_reduction_intercept was changed, this will generate different results for all FATES tests.  B4B tests were conducted on the FATES simulations by reverting that change and they PASSED. See https://github.com/NGEET/fates/pull/759

Any User Interface Changes (namelist or namelist defaults changes)?

Yes!  Here is the new fates default parameter file:

lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc

This file matches the version controled text file in the syncyhronized fates branch.

Testing performed, if any: regular
  ran against ctsm5.1.dev044
  now rerunning against ctsm5.1.dev045

### CODE REVIEW

**Comment by rgknox** [comment]
The new default parameter file has not yet been added to svn version control: 
lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc

**Comment by rgknox** [comment]
This branch contains changes that support #1182 and #1304, so this PR should be at the top of the FATES integration queue.

**Comment by rgknox** [comment]
Imported the new parameter file:

```
cseg/inputdata> ./rimport -file lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc
 
svn import  /glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc
Adding  (bin)  /glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc

Committed revision 35701.
```

**Comment by rgknox** [comment]
kicked off aux_clm tests on cheyenne and izumi, will report in

**Comment by rgknox** [comment]
izumi tests: /glade/scratch/rgknox/tests_0629-044715ch
cheyenne: /scratch/cluster/rgknox/tests_0629-045039iz

I "think" the test results are nominal... 
There are NLCOMP diffs with all the FATES tests, which is expected.  
BASELINE tests should not pass for FATES tests
Vnuopc tests seems to fail their sharedlib builds (but I remember from previous PR that those were  not working)

**Comment by rgknox** [comment]
The synchronized fates change is now undergoing modifications, will hold on this. Will re-test when these modifications are done.
@ckoven 
https://github.com/NGEET/fates/pull/759

**Comment by rgknox** [comment]
per requests in https://github.com/NGEET/fates/pull/759, I needed to create a new default fates parameter file in the svn repo.  Does anyone know the command to remove my first attempt? this one: lnd/clm2/paramdata/fates_params_api.16.1.0_12pft_c210628.nc

also, re-testing with the fates test suite, feel free to recommend other tests

**Comment by rgknox** [comment]
tests running:
/scratch/cluster/rgknox/tests_0701-100050iz
/glade/scratch/rgknox/tests_0701-095733ch

**Comment by ekluzek** [comment]
@rgknox I'd like to coopt your PR a bit to fix #1383. I'll push the changes to your branch, so you won't have to worry about it. It's also OK if you've already done the testing without it. It's an invisible change that only matters for a future version of cime. But, we just need it in place ASAP for CESM work. Let me know if that sounds OK.

**Review by ekluzek — APPROVED** [review]

**Pull request merged**
