### PR TITLE
Resolve pylint issues

### LINKED ISSUE #2255: make lint is not clean in ctsm5.1.dev152
### Brief summary of bug

We were aware of this when this came in. But, pylint is not clean with ctsm5.1.dev152 with #2156. This is something that @TeaganKing and others will work on in upcoming tags. The issues should just be in run_neon python code. It is black clean however at this point.

### General bug information

**CTSM version you are using:** ctsm5.1.dev152
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** 
### Important details of your setup / configuration so we can reproduce the bug

``` tcsh
./py_env_create
conda activate ctsm_pylib  
cd python
make lint
```

### Important output or errors that show the problem

``` text
(ctsm_pylib) cheyenne2 main_dev/python> make lint
pylint -j 4 --rcfile=ctsm/.pylintrc ctsm
************* Module ctsm.test.test_unit_modify_singlept_site_neon
ctsm/test/test_unit_modify_singlept_site_neon.py:21:0: C0413: Import "from ctsm.path_utils import path_to_ctsm_root" should be placed at the top of the module (wrong-import-position)
************* Module ctsm.test.test_sys_modify_singlept_site_neon
ctsm/test/test_sys_modify_singlept_site_neon.py:61:8: W0612: Unused variable 'parser' (unused-variable)
************* Module ctsm.test.test_sys_run_neon
ctsm/test/test_sys_run_neon.py:56:8: W0612: Unused variable 'parser' (unused-variable)
************* Module ctsm.site_and_regional.modify_singlept_site_neon
ctsm/site_and_regional/modify_singlept_site_neon.py:181:38: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:277:4: C0103: Variable name "f1" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:306:0: C0103: Argument name "nc" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:390:8: W0612: Unused variable 'index' (unused-variable)
ctsm/site_and_regional/modify_singlept_site_neon.py:416:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:417:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:444:11: W0703: Catching too general exception Exception (broad-except)
ctsm/site_and_regional/modify_singlept_site_neon.py:436:34: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:447:29: E1101: Instance of 'Exception' has no 'code' member (no-member)
ctsm/site_and_regional/modify_singlept_site_neon.py:450:0: C0103: Argument name "f2" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:478:0: C0116: Missing function or method docstring (missing-function-docstring)
ctsm/site_and_regional/modify_singlept_site_neon.py:512:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:516:4: C0103: Variable name "f1" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:560:-1: W0105: String statement has no effect (pointless-string-statement)
ctsm/site_and_regional/modify_singlept_site_neon.py:563:4: C0103: Variable name "f2" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:665:4: C0103: Variable name "f2" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/modify_singlept_site_neon.py:504:4: W0612: Unused variable 'current_dir' (unused-variable)
ctsm/site_and_regional/modify_singlept_site_neon.py:478:0: R0915: Too many statements (89/50) (too-many-statements)
************* Module ctsm.site_and_regional.run_neon
ctsm/site_and_regional/run_neon.py:354:0: C0325: Unnecessary parens after 'in' keyword (superfluous-parens)
ctsm/site_and_regional/run_neon.py:420:0: C0301: Line too long (122/100) (line-too-long)
ctsm/site_and_regional/run_neon.py:425:0: C0301: Line too long (121/100) (line-too-long)
ctsm/site_and_regional/run_neon.py:539:0: C0301: Line too long (126/100) (line-too-long)
ctsm/site_and_regional/run_neon.py:544:0: C0301: Line too long (125/100) (line-too-long)
ctsm/site_and_regional/run_neon.py:700:0: C0301: Line too long (151/100) (line-too-long)
ctsm/site_and_regional/run_neon.py:660:28: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:30: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:32: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:34: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:37: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:39: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:42: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:44: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:48: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:50: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:52: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:54: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:660:56: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:52: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:54: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:56: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:58: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:61: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:760:63: W1401: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
ctsm/site_and_regional/run_neon.py:69:0: E0401: Unable to import 'CIME' (import-error)
ctsm/site_and_regional/run_neon.py:69:0: C0413: Import "from CIME import build" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:70:0: E0401: Unable to import 'CIME.case' (import-error)
ctsm/site_and_regional/run_neon.py:70:0: C0413: Import "from CIME.case import Case" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:71:0: E0401: Unable to import 'CIME.utils' (import-error)
ctsm/site_and_regional/run_neon.py:71:0: C0413: Import "from CIME.utils import safe_copy, expect, symlink_force" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:73:0: C0413: Import "from ctsm.path_utils import path_to_ctsm_root" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:74:0: C0413: Import "from ctsm.utils import parse_isoduration" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:75:0: C0413: Import "from ctsm.download_utils import download_file" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:77:0: C0413: Import "from ctsm import add_cime_to_path" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:79:0: E0401: Unable to import 'standard_script_setup' (import-error)
ctsm/site_and_regional/run_neon.py:79:0: W0401: Wildcard import standard_script_setup (wildcard-import)
ctsm/site_and_regional/run_neon.py:79:0: C0413: Import "from standard_script_setup import *" should be placed at the top of the module (wrong-import-position)
ctsm/site_and_regional/run_neon.py:92:4: E0602: Undefined variable 'CIME' (undefined-variable)
ctsm/site_and_regional/run_neon.py:276:11: E0602: Undefined variable 'CIME' (undefined-variable)
ctsm/site_and_regional/run_neon.py:330:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
ctsm/site_and_regional/run_neon.py:384:20: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:385:20: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:437:12: C0103: Variable name "t0" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:439:12: C0103: Variable name "t1" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:449:8: C0103: Variable name "d1" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:450:8: C0103: Variable name "d2" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:453:4: R0201: Method could be a function (no-self-use)
ctsm/site_and_regional/run_neon.py:536:42: E0602: Undefined variable 'compset' (undefined-variable)
ctsm/site_and_regional/run_neon.py:558:31: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:564:31: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:467:4: R0915: Too many statements (86/50) (too-many-statements)
ctsm/site_and_regional/run_neon.py:648:16: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:660:12: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:664:20: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:666:27: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:704:45: C0103: Variable name "fd" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:378:8: W0201: Attribute 'base_case_root' defined outside __init__ (attribute-defined-outside-init)
ctsm/site_and_regional/run_neon.py:740:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:746:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:749:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/run_neon.py:785:12: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
ctsm/site_and_regional/run_neon.py:786:25: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:787:25: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:788:25: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:789:25: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:790:25: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:753:13: W0612: Unused variable 'item' (unused-variable)
ctsm/site_and_regional/run_neon.py:832:8: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
ctsm/site_and_regional/run_neon.py:860:24: W1202: Use lazy % formatting in logging functions (logging-format-interpolation)
ctsm/site_and_regional/run_neon.py:77:0: W0611: Unused add_cime_to_path imported from ctsm (unused-import)
ctsm/site_and_regional/run_neon.py:79:0: C0411: third party import "from standard_script_setup import *" should be placed before "from ctsm.path_utils import path_to_ctsm_root" (wrong-import-order)
************* Module ctsm.site_and_regional.neon_surf_wrapper
ctsm/site_and_regional/neon_surf_wrapper.py:89:4: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
ctsm/site_and_regional/neon_surf_wrapper.py:104:8: W0612: Unused variable 'i' (unused-variable)

-------------------------------------------------------------------
Your code has been rated at 9.74/10 (previous run: 10.00/10, -0.26)

Makefile:47: recipe for target 'lint' failed
make: *** [lint] Error 30
```

### PR DESCRIPTION
**Pull request by samsrabin**
### Description of changes
Resolve `pylint` issues in `python/ctsm/`.

### Specific notes

**Contributors other than yourself, if any:** None

CTSM Issues Fixed (include github issue #):
- Fixes #2255

**Are answers expected to change (and if so in what way)?** No

**Any User Interface Changes (namelist or namelist defaults changes)?** No

**Testing performed, if any:** As of 657cc5c45:
- `make lint` is clean
- `make black` is clean
- All tests passing in `make test`
- RXCROPMATURITY run passes
- `FSURDATMODIFYCTSM_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.derecho_intel` passes
- `clm_pymods` (just LILACSMOKE test) passes

### CODE REVIEW

**Comment by samsrabin** [comment]
@TeaganKing Tagging you on this because I know you've been working on the NEON Python code, two files of which this PR touches. I can revert those changes if you want, though.

**Comment by TeaganKing** [comment]
@samsrabin thanks for checking in with me! The `modify_singlept_site` work looks fine by me; it shouldn't affect what I'm currently working on!

**Comment by samsrabin** [comment]
Also tagging @slevis-lmwg, who was assigned on #2255.

**Review by adrifoster — APPROVED** [review]

**Comment by samsrabin** [comment]
Thanks, @adrifoster! I will plan to merge this after #2353, so for now marking it as blocked.

**Comment by samsrabin** [comment]
`FSURDATMODIFYCTSM_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.derecho_intel` works.

**Pull request merged**
