### PR TITLE
Document authorship and CTSM code management team, release branch

### PR DESCRIPTION
**Pull request by billsacks**
**Same as #1006 but for the release branch**

### Description of changes

- Add zenodo metadata file so that the Zenodo authorship is given simply as "CTSM Development Team", rather than trying to harvest authorship information from the list of git contributors.

- Document primary CTSM code management team members in the README

- Convert README to markdown, because I find it a little easier to work with than restructuredText. (Other than the addition of the CTSM code management team and fixing a link, content is the same as before.)

- Bring in a few other changes from the README file on master (making the README file on the release branch identical to that on master)

### Specific notes

Contributors other than yourself, if any: none

CTSM Issues Fixed (include github issue #):
- Addresses #1005 for release branch

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any: None

### CODE REVIEW

**Comment by billsacks** [comment]
@ekluzek this was approved for master. This one is for the release branch and I thought I'd let you merge it at your convenience, since you're the main one working with the release branch.

**Comment by olyson** [comment]
I don't see Peter Lawrence as part of the science team?

**Comment by billsacks** [comment]
@ekluzek just reviewing outstanding PRs. Any objection to merging this one into the clm5.0 release branch?

**Review by ekluzek — APPROVED** [review]

**Comment by ekluzek** [comment]
@olyson pointed out that @lawrencepj1 should be added to the science team. This should also happen on the main-dev branch as well.

**Pull request merged**
