### PR TITLE
Allow for resorbtion in transition from live to dead wood N

### PR DESCRIPTION
**Pull request by wwieder**
### Description of changes
allows for resorbtion in transition from live to dead wood N, which also move to NPOOL for free.

### Specific notes
allows resorbtion of live_to_dead wood N flux
moves live stem and root retranslocated N to NPOOL for free

Contributors other than yourself, if any:
This was first noticed in single point simulations by @susancheng. @rosiealice provided input & suggestions.

CTSM Issues Fixed (include github issue #):
#443 

Are answers expected to change (and if so in what way)?
All modifications increased GPP and CUE, resulting in higher LAI and VEG C pools, but the collateral changes to the C cycle seem minimized with these suggested changes here. Results seem to be behaving appropriately, with no excess N accumulating in RETRANSN and NPOOL, but is incorrectly being handled in CNNStateUpdate as presently implemented.

Any User Interface Changes (namelist or namelist defaults changes)?
none

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)
none

**NOTE: Be sure to check your Coding style against the standard:**
https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines
I'm sure I'll need to clean up some of this.

### CODE REVIEW

**Comment by wwieder** [comment]
This is all work that I did a while ago and never merged back into trunk.  After cleaning things up I'll make a clean comparison to check things are working sensibly.

**Comment by wwieder** [comment]
@ekluzek I'm guessing the case below is too old to rerun, it's from dev003 (maybe something to do with `p_old` vs. `p_new`).  But I'd like to look at a few simulations before cleaning up this PR.
Currently I get this error when running `preview_namelist`
`Invalid values ['10800.0']`
`ERROR: Variable 'coupling_period' has invalid value ['10800.0'].`

/glade/work/wwieder/ctsm/ctsm1.0.dev003/cime/scripts/clm5_4x5_woodCN_tests_5a_freeRetrans_50_500_spin

Do I need to update to a current tag to be able to re-run?  Can I do this easily without reverting my changes by just checking out from master and migrating changes to src?

**Comment by ekluzek** [comment]
@wwieder actually that is an easy thing to fix. It just has to do with an easy python 2 to python 3 fix. And actually if you run with python 2, you wouldn't likely have to change anything.

I think that error is just in the ROF component. So you probably just need to update MOSART to the latest (which shouldn't change answers). So that would be an easy thing to do.

**Comment by wwieder** [comment]
additional testing done with updated code base in #1063

**Pull request closed without merging**
