### PR TITLE
Merge b4bdev 20240827

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Bring b4b-dev branch to main CTSM development.

- PLUMBER2 for ctsm5.2 datasets
- Last bit of PPE changes for namelist and parameter file settings
- Update run_sys_tests on Derecho for compiler jobs to run using 16 tasks
- Bring in a fix for dust emissions for coupling with CAM

### Specific notes

Contributors other than yourself, if any: @TeaganKing @wwieder @slevis-lmwg @samrabin

CTSM Issues Fixed (include github issue #):
  Already listed in individual PR's to b4b-dev, will close when it comes to main dev.

Are answers expected to change (and if so in what way)? No bit-for-bit

Any User Interface Changes (namelist or namelist defaults changes)? Yes
  Changed behavior for build-namelist command line options: -drydep, -megan, and -fire_emis
     Turning them on now only adds test namelists to use, you can add custom settings for them in user_nl_clm
      with or without them on
  Using PLUMBER2 user-mods now gives you ctsm5.2 surface datasets

  New parameter file with c3psn corrected and ndays_on changed to PFT
     new parameters: crit_onset_gdd_sf, zbedrock, zbedrock_sf

Does this create a need to change or add documentation? Did you do so? Yes and Yes

Testing performed, if any: will do regular testing
  build-namelist and python testing has been done so far

### CODE REVIEW

**Review by slevis-lmwg — APPROVED** [review]
@ekluzek thank you for working on this. I'm clicking approve.

**Comment by wwieder** [comment]
This is awesome.  Thanks for bringing this in, @ekluzek .

One note, since the PLUMBER2 work is on main now we'll also need to recreate these surface datasets.  I'm assuming this needs to get done early in the 5.3 series (or maybe on the 5.3 tag), but I'll add the issue to #2500.

**Comment by ekluzek** [comment]
Testing seemed to get stuck on both Izumi, and Derecho, so I had to resend testing with --rerun-existing-failures for it. That rerun stint is still going, so we'll see if it finished in the morning...

**Comment by ekluzek** [comment]
@fischer-ncar OK, still issues with the testing for some reason. I probably need to look at each one and see what's going on. There at least one test on Izumi, that I had to clean the build, before the build could run successfully. I probably have to do that with others. There might be similar things I need to do on Derecho. I'm not convinced that starting testing over would fix the problem, so I'll see if I can make progress by resending individual tests...

**Comment by ekluzek** [comment]
Both on Derecho and Izumi I get fails like this:

```
Running cmake for CDEPS
/glade/derecho/scratch/erik/tests_ctsm5227acl/sharedlibroot.ctsm5227acl_int/intel/mpich/debug/nothreads/CDEPS already exists, checking for lockfile
ERROR:  Timeout waiting for /glade/derecho/scratch/erik/tests_ctsm5227acl/sharedlibroot.ctsm5227acl_int/intel/mpich/debug/nothreads/nuopc/CDEPS/dwav/libdwav.a(ctsm_pylib) tests_ctsm5227acl/ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust.GC.ctsm5227acl_int> 
```

I didn't see this before on b4b-dev, but we do have CDEPS updated, so maybe there is a potential race condition in building that can show up?

**Comment by ekluzek** [comment]
OK, Mike Levy suggested I update the CDEPS tag to the next one to get around this. So I'm going to do that.

At the same time I see unexpected differences compared to baseline in quite a few tests that are significant size in lots of variables.

**Comment by ekluzek** [comment]
Testing is working fine now and finished as expected on Izumi. Derecho is still running. The update for CDEPS fixed the build problem I had. I also realized my mistake about change of answers on Izumi, and no longer seeing that. So this is almost there...

**Pull request merged**
