### PR TITLE
Implementing GEOS-Chem chemistry in development (CESM2-GC)

### PR DESCRIPTION
**Pull request by fritzt**
Hello! 

I have been working on implementing the GEOS-Chem (version 13.0.0) chemistry module in CESM2.1.1. This new option is designated as CESM2-GC. The implementation of GEOS-Chem chemistry inside CESM2 aims to provide an additional chemistry option alongside CAM-Chem. 

This is the second PR out of three (CAM, CLM, cime). The main PR can be found at https://github.com/ESCOMP/CAM/pull/378

### Description of changes

This PR focuses on passing land types and leaf area indices (LAI) from CLM to CAM through the coupler. I followed the same workflow as what is done for albedo. The land types and LAI are required in CAM to let GEOS-Chem compute its own dry deposition velocities.

### Specific notes

Contributors other than yourself, if any: None

CTSM Issues Fixed (include github issue #): None

Are answers expected to change (and if so in what way)? 
No, this PR introduces changes that only aim to pass information from CLM to CAM.

Any User Interface Changes (namelist or namelist defaults changes)?
No.

Testing performed, if any:
I was able to output land types and LAI as archived by CAM.

------------------------------------------------------------------------

Let me know if I am targetting the wrong branch. The CLM tag I used for my work is `release-clm5.0.25`. Attached is the top-level `Externals.cfg` that I used for my project.

Regards,
Thibaud Fritz
Laboratory for Aviation and the Environment

[Externals.txt](https://github.com/ESCOMP/CTSM/files/6504977/Externals.txt)

### CODE REVIEW

**Comment by ekluzek** [comment]
@fritzt thanks for the contribution. 

I'm just wondering why you want this in CESM2.1 instead of the latest development version CESM2.3? CESM2.1 is considered closed in terms of development. We likely will have some continued support for it, but I didn't think that was to continue very long. And as such I would think new developments should go into the latest development code base of CESM2.3.

The other point is that the latest CESM2.1 version for CLM is release-clm5.0.34. So you should update this branch from release-clm5.0.25 to release-clm5.0.34 using git. You don't have to create a new PR, you can just do the update, commit the changes and push them to the branch and they'll show up in the PR.

**Comment by fritzt** [comment]
Thank you for the feedback @ekluzek!

I started out this project working on CESM2.1.1 but I'm more than happy to merge this into CESM2.3. I also believed that CESM2.1.1 was using the `release-clm5.0.25` tag (as shown here https://github.com/ESCOMP/CESM/blob/release-cesm2.1.1/Externals.cfg).

I believe I have applied all the commits up to `release-clm5.0.34`.

**Comment by mvertens** [comment]
@fritzt - another issue to consider if you do a PR to the latest development version is that we are migrating to the NUOPC/CMEPS coupler as the default framework in the near future - so these changes also need to be implemented in the nuopc cap (in src/cpl/nuopc). I am happy to talk to you about how to do that and also help with questions. The same thing will need to be done for the new coupler (now called a mediator) and cam.

**Comment by ekluzek** [comment]
Hmmm. So I'm seeing a huge number of differences in files that I'm doubtful that you've touched. So I'm wondering if your merge update to release-clm5.0.34 worked correctly?

**Comment by ekluzek** [comment]
@fritzt are there CESM collaborators you are working with on this that we can talk to about this project? Maybe people in the Chemistry working group for example? Getting this on the latest release-clm5.0 is a good first start, but it still really might make the most sense for it to be on the latest development version. Doing that will take some effort, so I'd like to make sure that's the correct thing to do.

If that is the right thing to do, we should evaluate if using git is the best way to go or if moving the code into by hand into the latest version makes the most sense. If you do it in git the next merge I'd recommend would be to ctsm1.0.dev106 as that brought the release-clm5.0 changes to the development version. Depending on how that goes you might go to the very latest after that or break it up into sections.

**Comment by fritzt** [comment]
I have been exchanging with a few people in ACOM, mostly Louisa Emmons, as well as Steve Goldhaver in CGD. Tagging @gold2718

Whatever works best! Feel free to cherry-pick my commits to any branch!

**Comment by ekluzek** [comment]
Hi @fritzt I talked with Louisa and she clarified that the plan is to bring this work into the latest development version of CESM. And there is no need to bring it into the CESM2.1 release. So I renamed the title of this to reflect that.  You will need to figure out the best way to go forward for you to bring this into the development version rather than the release version. I see a couple different ways forward. As such it might be best if we have a few of us talk it over with you. I suggest starting with Louisa talk it over with her, and then setup a meeting with us in CTSM to go over your plan when needed.

**Comment by lizziel** [comment]
You are correct that CESM-GC_dev2 is the branch with the changes. I now see all three `main/` files in the `master` branch. That was a lower-case "L" looking like capital "I" error on my part.

I am going to take a look at all the relevant files and I'll let you know if I have questions / want to set up a meeting. I have a meeting set up already about this work with Steve Goldhaber on Thursday. That meeting covers this and other PRs from @fritzt for cam and cime. Would it make sense for you to join?

**Comment by ekluzek** [comment]
@lizziel yes joining your Thursday meeting might make sense. I'm happy to join if it works with the other meetings I have that day. If we could make the discussion of this PR first, then I could bail when you get to the other topics. We could use that meeting time as a basis of if we need another meeting with more people. Go ahead and send me the gcal invite for it, and I'll see if I can come.

**Comment by lizziel** [comment]
I created new PR https://github.com/ESCOMP/CTSM/pull/1475 to supercede this PR. Per guidance from @ekluzek I made all updates to analogous files changed in the original update with the exception of the NUOPC layer. The update for NUOPC will be made in a later commit in that PR following further discussion.

**Comment by ekluzek** [comment]
@lizziel since #1475 supersedes this, I'm closing it. It'll still hang around and if for some reason we need to reopen it we can.

**Pull request closed without merging**
