### PR TITLE
Updated path to fates default parameter file

### PR DESCRIPTION
**Pull request by rgknox**
### Description of changes

This updates the path to the default parameter file for FATES.  This file matches new specifications designed in https://github.com/NGEET/fates/pull/418.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?

Answers should change in FATES only, and they should only be of scales associated with rounding errors or order of operations.

Any User Interface Changes (namelist or namelist defaults changes)?

New parameter file.

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for gnu/pgi and hobart for gnu/pgi/nag is the standard for tags on master)

fates test suite, non-comparison, cheyenne, intel:   all PASS

**NOTE: Be sure to check your Coding style against the standard:**
https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines

### CODE REVIEW

**Comment by rgknox** [comment]
I have not run rimport, still awaiting approval on https://github.com/NGEET/fates/pull/418

**Comment by ekluzek** [comment]
To be complete this will also have an update to the fates version it points to in order to utilize the changes in the params file.

**Comment by rgknox** [comment]
@ekluzek , I have no further changes to add to this PR.

I have also imported /glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/fates_params_default_2trop.c180921.nc

**Comment by ckoven** [comment]
this all looks good to me.

**Pull request merged**
