### PR TITLE
updates to FATES test category

### PR DESCRIPTION
**Pull request by rgknox**
This PR updates the FATES category test suite.  Entries were modified by adding lawrencium-lr3 and the intel compiler as a valid machine/compiler combination.  The specific tests run as part of the fates test category were modified as well.

This PR also updates the default parameter file for fates, one entry was changed, thereby changing the freezing tolerance parameter from a dummy value to a nominal value of 0 degrees for tropical trees.

Summary of test changes,  one test was fixed to use the clm default testmod dir because it was not a fates simulation. Various other tests were changed from fates-clm45 to fates-clm50, one test was left to remain a fates-clm45 test.

Here is the updated list for the fates category:

```
ERP_D_Ld3.f19_g16.I2000Clm50FatesCruGs.<>.clm-FatesColdDef
ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.<>.clm-FatesColdDef
ERP_Ld3.f09_g16.I2000Clm45Fates.<>.clm-FatesColdDef
ERP_Ld9.f45_f45.I2000Clm50FatesCruGs.<>.clm-FatesAllVars
ERS_D_Ld3.f19_g16.I2000Clm50FatesCruGs.<>.clm-FatesColdDef
ERS_D_Ld5.f19_g16. I2000Clm45BgcCrop.<>.clm-default
ERS_D_Ld5.f19_g16.I2000Clm50BgcCruGs.<>.clm-default
ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesCruGs.<>.clm-FatesColdDef
ERS_Ld5.f19_g16.I2000Clm45Fates.<>.clm-FatesColdDef
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-Fates
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-FatesLogging
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-FatesNoFire
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-FatesPPhys
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-FatesST3
SMS_Lm6.f45_f45_mg37.I2000Clm50FatesCruGs.<>.clm-Fates
SMS_Ly2.1x1_brazil.I2000Clm50FatesCruGs.<>.clm-FatesColdDef
```

Addresses Issues: #221 

Review/Collaborators:

Tests: fates test group on lawrencium (work in progress).

FATES hash: 5c40b26 (fates_s1.4.1_a3.0.0_rev3 default pointer HEAD)

### CODE REVIEW

**Comment by rgknox** [comment]
Well, these tests are definitely not doing much passing, but I wanted to get the PR up and running.
Here are the results from the updated fates group on lawrencium (no baseline):

PASS:
```
SMS_Ly2.1x1_brazil.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates 
```

Submit FAIL:
```
FAIL ERP_D_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef SUBMIT
FAIL ERP_D_P15x2_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates SUBMIT
FAIL ERS_D_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates SUBMIT
FAIL ERS_D_Ld5.f19_g16.I2000Clm50BgcCruGs.lawrencium-lr3_intel.clm-default SUBMIT
```

Run FAIL:
```
FAIL ERS_Ld60.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates RUN time=9
FAIL ERS_Ld60.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesLogging RUN time=5
FAIL ERS_Ld60.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesNoFire RUN time=5
FAIL ERS_Ld60.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesPPhys RUN time=5
FAIL ERS_Ld60.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesST3 RUN time=5
FAIL SMS_Lm6.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates RUN time=5
```

COMPARE_base_rest FAIL:
```
FAIL ERP_Ld3.f09_g16.I2000Clm45Fates.lawrencium-lr3_intel.clm-FatesColdDef COMPARE_base_rest
FAIL ERP_Ld9.f45_f45.I2000Clm45Fates.lawrencium-lr3_intel.clm-FatesAllVars COMPARE_base_rest
FAIL ERS_D_Ld5.f19_g16.I1850Clm45BgcCruGs.lawrencium-lr3_intel.clm-default COMPARE_base_rest
FAIL ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates COMPARE_base_rest
FAIL ERS_Ld5.f19_g16.I2000Clm45Fates.lawrencium-lr3_intel.clm-FatesColdDef COMPARE_base_rest
```

**Comment by rgknox** [comment]
Looks like a bunch of the submit fails were due to missing data, via: atm_forcing.datm7.cruncep_qianFill.0.5d.v7.c160715

Will work on getting that squared away first.

**Comment by rgknox** [comment]
Looks like some (maybe all) of the RUN fails are occuring because of an incompatibility with:

Note that I did not update the grid on the tests from f45_f45 to f45_f45_mg37...

/global/scratch/rgknox/cesm_input_datasets//lnd/clm2/initdata_map/clmi.I2000Clm45Fates.0121-01-01.4x5_mgx3v7_simyr2000_c180122.nc

**Comment by rgknox** [comment]
FYI, @ekluzek , @bjandre , some of the clm_aux tests were using the "Fates" testmod dir.  The fates testmod dir activates an finidat initialization, which @billsacks and I thought was maybe something to only enforce on the fates test category.  It seems overly onerous to keep up-to-date fates finidat files considering the restart variables would be changing for two different models (ctsm/fates).
I am going to set the fates tests in clm_aux to use FatesColdDef as the testmodir, which has no finidat initialization, unless you guys want it otherwise.

**Comment by billsacks** [comment]
Thanks, @rgknox - @ekluzek and I agreed a few days ago that we should use FatesColdDef for all of the fates tests in the aux_clm suite. I'm happy for you to change that as part of this PR.

**Comment by rgknox** [comment]
Will do.

**Comment by rgknox** [comment]
In cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm

I see that the finidat is maybe commented out, but maybe not?  Is this being set somewhere else?  I noticed that if I set it to a new file, it is being overwritten and a different file is ultimately appearing in lnd_in for finidat.

**Comment by billsacks** [comment]
@rgknox Yes, "!" is a comment character in these user_nl files. This is set in `bld/namelist_files/namelist_defaults_clm4_5.xml`. @ekluzek said he moved the setting there so that the testmods directory wouldn't be tied to a specific resolution.

We'll need to coordinate any updates to the initial conditions files, because they need to be updated for #311 , too.

**Comment by rgknox** [comment]
ok, thanks.  Thats a nice feature @ekluzek 

So test that meets the conditions described in namelist_defaults_clm4_5.xml, ie:
```
<finidat hgrid="4x5"  maxpft="17"  mask="gx3v7" use_cn=".false." use_fates=".true."
         ic_ymd="20000101"  use_nitrif_denitrif=".false." use_vertsoilc=".true." sim_year="2000"
         ic_tod="0" glc_nec="10" use_crop=".false." irrigate=".true."
>lnd/clm2/initdata_map/clmi.I2000Clm45Fates.0121-01-01.4x5_mgx3v7_simyr2000_c180122.nc                     

```
Will append that file as the finidat?

If a different finidat file, or a specified blank file, is listed in the user_nl_clm in the testmod dirs, will that over-ride this?

**Comment by billsacks** [comment]
@rgknox yes, that's right - and yes, user_nl_clm will override this.

**Comment by rgknox** [comment]
For fates developer tests, I wanted to include 1 test to check if we broke non-fates clm45.  Could you all recommend an acceptable generic compset to meet this end?

I had previously been using the I1850Clm45BgcCruGs compset, but I would rather avoid an I1850 as it requires a whole different met driver set than the I2000s.

**Comment by billsacks** [comment]
I2000Clm50BgcCrop is probably a good choice.

**Comment by billsacks** [comment]
Oh, just saw your edit. Your suggestion is fine, too, if you're deliberately keeping most tests with Clm45 rather than Clm50.

**Comment by rgknox** [comment]
I will do one of each clm45 and clm50, non-fates.  I could add more key non-fates tests to the fates category.  Although, I assume for fates integrations into ctsm, there will be plenty more non-fates testing through other categories.

**Comment by rgknox** [comment]
Here is an update on the tests.  There is certaintly work to do to get FATES-ctsm passing across the board.

All PASS:
```
  ERP_D_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef
  ERP_Ld3.f09_g16.I2000Clm45Fates.lawrencium-lr3_intel.clm-FatesColdDef
  ERS_D_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef
  ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef
  ERS_Ld5.f19_g16.I2000Clm45Fates.lawrencium-lr3_intel.clm-FatesColdDef
  SMS_Lm6.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates
  SMS_Ly2.1x1_brazil.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef
  ERS_D_Ld5.f19_g16.I2000Clm45BgcCrop.lawrencium-lr3_intel.clm-default
```
RUN Fails:
```
FAIL ERP_D_P32x2_Ld3.f19_g16.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesColdDef RUN time=39
FAIL ERS_D_Ld5.f19_g16.I2000Clm50BgcCruGs.lawrencium-lr3_intel.clm-default RUN time=173

```

Restart Compare Fails:
```
    FAIL ERP_Ld9.f45_f45.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesAllVars COMPARE_base_rest
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-Fates COMPARE_base_rest
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesLogging COMPARE_base_rest
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesNoFire COMPARE_base_rest
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesPPhys COMPARE_base_rest
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruGs.lawrencium-lr3_intel.clm-FatesST3 COMPARE_base_rest
```

These restart compare fails had not been passing with our previous land-model driver "fates-clm".  These are all the non cold-start runs.

**Comment by rgknox** [comment]
@ekluzek , what next steps would you like to see or discuss?  Is there a place I should document expected fails?
Any modifications? next tests?

**Comment by rgknox** [comment]
I do have one more step to perform, the finidat file listed in the defaults needs to be updated and loaded to svn.  Will update.

**Comment by rgknox** [comment]
Loaded:  /glade/p/cesm/cseg/inputdata/lnd/clm2/initdata_map/clmi.I2000CLM50FATESCRUGS.0006-01-01.f45_f45_mg37_s1.4.1_a3.0.0_rev3_c180316.nc

I have not run rimport on it yet, pending any suggestions.

This PR and its tests meet expectations on my side.  Some FAILS are expected, and some will need to be worked through in separate threads.

**Pull request merged**
