### PR TITLE
Remove unused variable elevclass_o in mkglcmecMod.F90

### LINKED ISSUE #2802: Array elevclass_o in mksurfdata_esmf/src/mkglcmecMod.F90 is not allocated before use.
### Brief summary of bug

Allocatable array elevclass_o in mksurfdata_esmf/src/mkglcmecMod.F90 is not allocated before use.
I'm not clear though whether this statement effectively accomplishes that:
```
    elevclass_o(:) = elevclass(:)
```

### General bug information

**CTSM version you are using:** ctsm5.3.0

**Does this bug cause significantly incorrect results in the model's science?** Unknown

**Configurations affected:** Surface dataset creation.

### Details of bug

Reported by Yuan Sun (https://bb.cgd.ucar.edu/cesm/threads/mksurfdata_esmf-done-around-glcmec.9624/#post-57405)

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes

User found that the mksurfdata_esmf tool fails on a certain computer with this error:
`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`
and works when elevclass_o gets allocated before use in mkglcmecMod.F90.

Original post here:
https://bb.cgd.ucar.edu/cesm/threads/mksurfdata_esmf-done-around-glcmec.9624/post-57405

### Specific notes

Contributors other than yourself, if any:
@olyson and @YuanSun-UoM

CTSM Issues Fixed (include github issue #):
Resolves #2802 

Are answers expected to change (and if so in what way)?
No.

Any User Interface Changes (namelist or namelist defaults changes)?
No.

Does this create a need to change or add documentation? Did you do so?
No.

Testing performed, if any:
As posted in issue #2802, I'm testing on derecho...
PASS qsub mksurfdata_jobscript_single_2000.sh so as to compare today's output to that generated yesterday, now in /glade/derecho/scratch/slevis/temp_work/new_rawdata/tools/mksurfdata_esmf/bkup_T42
PASS ./run_ctsm_py_tests -s and ./run_ctsm_py_tests -u
PASS make black and make lint
PASS build-namelist_test.pl
IN PROGRESS aux_clm

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
Now also started aux_clm on izumi.

**Review by ekluzek — CHANGES_REQUESTED** [review]
@slevis-lmwg I actually recommend that you remove elevclass_o completly rather than allocate it.  There seems to be no reason for it to exist.

In terms of testing I would make an f09 surface dataset and also run the MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel and compare it to the baseline. That's the only aux_clm test that's going to exercise this bit of code.

**Comment by slevis-lmwg** [comment]
1) Removed the variable.
2) Started `./create_test MKSURFDATAESMF_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel -c /glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.002`
3) Rebuilt mksurfdata_esmf after removing the variable.
4) Submitted `qsub mksurfdata_jobscript_single_2000.sh` this time pointing to `crop-global-present_0.9x1.25.namelist` which was used to generate the corresponding ctsm5.3.0 files.

**Comment by slevis-lmwg** [comment]
The above tests passed, so this is ready.

**Comment by slevis-lmwg** [comment]
@ekluzek thank you, I followed your suggestions and the tests pass. Let me know if you can think of anything else before approving.

**Review by olyson — APPROVED** [review]

**Review by ekluzek — APPROVED** [review]

**Pull request merged**
