### PR TITLE
updates for memory scaling

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Reduces the initialization memory footprint of ctsm.

### Specific notes

Contributors other than yourself, if any: mvertens (primary developer)

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)?  No

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by ekluzek** [comment]
@jedwards4b and @mvertens is this ready to go at this point? Or is more development needed for this? I'm wondering if it should be taken out of draft mode for one...

This sounds like a nice update in principle, memory scaling would be really helpful especially for high resolutions grids.

Also I noticed there is a DEBUG CPP token added in. We don't really have a debug mode connected into the build for mksurfdata_esmf, see #1775. So I'm assuming this isn't working, unless there's some other mechanism to turn it on. Can you talk about that?

**Comment by ekluzek** [comment]
Ahh, OK, for some reason I assumed that if it was from @mvertens it was about mksurfdata_esmf.  I thought I saw some commits that referenced it, but obviously must not have see it correctly. Thanks for running testing, I have a tag that should be out today, but we'll bring this in when ready.

**Comment by mvertens** [comment]
@ekluzek - I did this work before I left but did not have time to fully test it within a full auxclm test suite.
@jedwards4b - thanks for seeing this PR through. Hopefully, it will help at least some of the issues that Chris was seeing.
He still ran into memory problems even after this - but I'm not sure how much work there still was done to understand that.

**Comment by jedwards4b** [comment]
Test Results: nag on Izumi with comparison to ctsm5.1.dev114 gives one failure, the RUN_STARTDATE has changed for this case: 
  ./cs.status.20221114_090345_i4v1sf -f -x ~/ctsm/cime_config/testdefs/ExpectedTestFails.xml 
20221114_090345_i4v1sf: 29 tests
    FAIL SMS_D_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO NLCOMP
    FAIL SMS_D_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-default--clm-NEON-NIWO BASELINE ctsm5.1.dev114: DIFF

and for intel on cheyenne: 
 ./cs.status.20221114_084136_97bfbr --fails-only -x ~/sandboxes/ctsm/cime_config/testdefs/ExpectedTestFails.xml 
20221114_084136_97bfbr: 120 tests
    FAIL DAE_N2_D_Lh12_Vmct.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.clm-DA_multidrv TPUTCOMP Error: TPUTCOMP: Computation time increase > 25% from baseline
    FAIL ERP_P144x2_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-mimicsFatesCold BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERP_P36x2_D_Ld5.f10_f10_mg37.I2000Ctsm50NwpBgcCropGswp.cheyenne_intel.clm-default BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERP_P36x2_D_Ld5.f10_f10_mg37.I2000Ctsm50NwpSpGswp.cheyenne_intel.clm-default BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERP_P36x2_Ld30.f45_f45_mg37.I2000Clm51FatesSpCruRsGs.cheyenne_intel.clm-FatesColdSatPhen BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-FatesColdFixedBiogeo BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-FatesColdSizeAgeMort BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL ERS_Ld9.f10_f10_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdCH4Off BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL SMS_D_Ld1_PS.f09_g17.I1850Clm50BgcSpinup.cheyenne_intel.clm-cplhist RUN time=54 (EXPECTED FAILURE)
    FAIL SMS_Ld5.f10_f10_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-FatesCold BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL SMS_Lm1_D.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-output_crop_highfreq BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing
    FAIL SMS_Ly1_Mmpi-serial.1x1_brazil.IHistClm50BgcQianRs.cheyenne_intel.clm-output_bgc_highfreq BASELINE ctsm5.1.dev114: ERROR BFAIL some baseline files were missing

**Comment by ekluzek** [comment]
This would be expected, ctsm5.1.dev114 isn't quite tagged yet and changes answers for NEON tests. So for your purposes don't worry about this for now.

**Review by ekluzek — APPROVED** [review]
Sorry this got forgotten and neglected. But, bringing in now.

**Pull request merged**
