### PR TITLE
Removing checks for dompft and include-nonveg

### PR DESCRIPTION
**Pull request by negin513**
### Description of changes
Previously `subset_data` explicitly checked to make sure the user has chosen at least one of the following options:
 1) dominant pft(s)    or 
 2) --include-nonveg (overrides default setting non-veg units to 0%)

However, @adrifoster pointed out that this limits FATES users who would not want to set a dominant pft(s) and would also want all 100% vegetated at the single point. So I removed this capability. 

 
### Specific notes

Contributors other than yourself, if any: @adrifoster 

CTSM Issues Fixed (include github issue #): #1707

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:

### CODE REVIEW

**Comment by adrifoster** [comment]
Thank you @negin513!!

**Comment by negin513** [comment]
I think this check was originally proposed in subset_data to avoid an error when we are zeroing-out non-vegetation land units:

https://github.com/ESCOMP/CTSM/blob/449345ee9a534316cba0d6b4fd696b8d57e60428/python/ctsm/site_and_regional/single_point_case.py#L430-L450

Currently I put in a check to avoid this error. However this means that when the user does not specify `dompft` and `include_nonveg`, we are zero-ing out `PCT_LAKE`, `PCT_WETLAND` , `PCT_URBAN` , and ` PCT_GLACIER`, but we are not changing `PCT_CROP` or `PCT_NATVEG`. This means that the sum of PCT landunits would not add up to 100. Wouldn't that be problematic when running CTSM?

**Comment by ekluzek** [comment]
Yes, not having the sum of PCT landunits adding up to 100 will cause the model to abort. That is a requirement of the surface datasets that is checked for.

**Comment by adrifoster** [comment]
My suggestion from the bug is to:

As for the problem with PCT_NATVEG and PCT_CROP:

Could you grab the current percentages of those values and then re-calculate the new percentage? (e.g. if we have 30% nat veg and 10% crop, the new zero-nonveg percentages would be 30/(30 +10)*100 for nat veg and 10/(30 + 10)*100 for crop

EDIT: added *100 for the percentages

**Comment by negin513** [comment]
Thanks @ekluzek and @adrifoster. 

Then there are two possible solution to avoid this:
1- I really like @adrifoster's suggestion to calculate new percentages after zeroing-out not vegetation landunits. 

2-  My original suggestion to avoid this was using a default `dompft`, but I remember there were some  issues against using a default pft. (from #1707)

I like Adrianna's suggestion better and I already implemented it. :grinning: My only concern is that now there are a lot of if else in this part of the code, but it should be okay. I tried clearing it up with a comment.
```python
        if not self.include_nonveg:
            logger.info("Zeroing out non-vegetation land units in the surface data.")
            f_mod["PCT_LAKE"][:, :] = 0.0 
            f_mod["PCT_WETLAND"][:, :] = 0.0 
            f_mod["PCT_URBAN"][:, :, :] = 0.0 
            f_mod["PCT_GLACIER"][:, :] = 0.0 
                    
            if self.dom_pft is not None:
                max_dom_pft = max(self.dom_pft)
                if max_dom_pft < NAT_PFT:
                    f_mod["PCT_NATVEG"][:, :] = 100 
                    f_mod["PCT_CROP"][:, :] = 0 
                else:
                    f_mod["PCT_NATVEG"][:, :] = 0 
                    f_mod["PCT_CROP"][:, :] = 100 
            else:
                #-- recalculate percentages after zeroing out non-veg landunits                                                                                                    
                #-- so they add up to 100%.
                tot_pct = f_mod["PCT_CROP"]+f_mod['PCT_NATVEG']
                f_mod ["PCT_CROP"] = f_mod ["PCT_CROP"]/tot_pct * 100 
                f_mod ["PCT_NATVEG"] = f_mod ["PCT_NATVEG"]/tot_pct * 100 
                    
        else:       
            logger.info(
                "You chose --include-nonveg --> \
                Do not zero non-vegetation land units in the surface data."
            ) 
```

**Comment by adrifoster** [comment]
> My only concern is that now there are a lot of if else in this part of the code, but it should be okay. I tried clearing it up with a comment.

Sometimes unavoidable! I think it's fine (only 3 blocks here). Thanks for doing this!

**Comment by ekluzek** [comment]
@negin513 you are right that complex if-then logic is hard to get right, and it's good to make it simpler if possible. But, as @adrifoster points out it's likely unavoidable here. Comments help as you have done. 

These complex logic parts of the code are things where it's good to have some unit testing in place to make sure that it's right -- because it's so easy to get it wrong. So I would suggest that you have some unit testing around it.

**Comment by adrifoster** [comment]
> To fix the logic, I suppose the check will need to be min_dom_pft, and an extra "elif" added for max_dom_pft< crop, and then the else for the mixed, crop and nat-veg case.

I agree I think this is a good way forward. For the mixed case, can we just use the input `pct_pft` to get the relative percentages?

**Comment by ekluzek** [comment]
Yes, exactly that would be the right thing to do. And then there will need to be a sum over the crop pfts and the nat-veg pft's to figure out how much is in each type. And actually the mixed case is the most general case, so you could get rid of the ifs and always do the mixed case. It might be more clear with the ifs in place though...

**Comment by negin513** [comment]
> For example, if I have my `dompft` list as [1,2,5,20] the max value would be a crop PFT, but we also have some naturally vegetated PFTs - so we can't assume 100% crop. Perhaps this was already discussed and this is not a likely scenario?

Hello Adrianna, Thanks for bringing up this point. Mixed land units is not possible with subset_data; therefore, the user cannot choose landunits that are both above and below 15. For example, if the user choose [1, 2, 5, 20], the code will automatically abort. 

Here is where we explicitly check to make sure this never happens:

https://github.com/ESCOMP/CTSM/blob/82a63cc16a451f06a79a2d4417058cbda819e766/python/ctsm/site_and_regional/single_point_case.py#L201-L213

You should be able to test it and get the same error.

**Comment by adrifoster** [comment]
> Mixed land units is not possible with subset_data;

Ah I missed that okay. Hmm, is this something we want to exclude? It seems like @ekluzek was saying the mixed case might be common.

**Comment by negin513** [comment]
> > Mixed land units is not possible with subset_data;
> 
> Ah I missed that okay. Hmm, is this something we want to exclude? It seems like @ekluzek was saying the mixed case might be common.

I think so. I remember I explicitly asked about this in the previous PR and I heard multiple times that we don't want mixed land units.

**Comment by adrifoster** [comment]
> I think so. I remember I explicitly asked about this in the previous PR and I heard multiple times that we don't want mixed land units.

Ah okay. Well perhaps in the interest of time (upcoming tutorial) we leave it as is for now and revisit later if this is something we want to support.

**Comment by ekluzek** [comment]
Ahhh, that makes sense now. You wouldn't have that mixed case for a tower site. So the only reason to support it would be for a more theoretical case, which could be useful, but, probably isn't really needed.

**Pull request merged**
