### PR TITLE
fates hydro compatibility

### PR DESCRIPTION
**Pull request by rgknox**
This PR does 3 things for fates hydro compatibility:

1) updates the default parameter file used in regression tests
2) add the fates hydro testmod (but intentionally does not add new tests to any lists)
3) adds two bug-fixes to the fateshydro interface.

This PR is paired with https://github.com/NGEET/fates/pull/343  .  This is NOT a coupled API PR, aside from this is needed to run regression tests with the FATES PR 343.

### CODE REVIEW

**Comment by rgknox** [comment]
When https://github.com/NGEET/fates/pull/343 is merged, I will update the external model pointer.

**Comment by rgknox** [comment]
I tried to run a test running manage_externals, and ran into the following error:

> ./manage_externals/checkout_externals

> cat manage_externals.log

```
t_n01_cism2_1_develop_n02']
INFO : 2018-05-21 13:37:31 : svn switch https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02
INFO : 2018-05-21 13:37:31 : run time : 0.10 seconds
DEBUG : 2018-05-21 13:37:31 : svn: E155007: '/glade/u/home/rgknox/ctsm/components/cism/glimmer-cism' is not a working copy
DEBUG : 2018-05-21 13:37:31 : 
ERROR : 2018-05-21 13:37:31 : Command '[u'svn', u'switch', u'https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02']' returned non-zero exit status 1
DEBUG : 2018-05-21 13:37:31 : svn: E155007: '/glade/u/home/rgknox/ctsm/components/cism/glimmer-cism' is not a working copy
DEBUG : 2018-05-21 13:37:31 : 
ERROR : 2018-05-21 13:37:31 : Failed with output:
    svn: E155007: '/glade/u/home/rgknox/ctsm/components/cism/glimmer-cism' is not a working copy

ERROR: In directory
    /glade/u/home/rgknox/ctsm/components/cism/glimmer-cism
Process did not run successfully; returned status 1:
    svn switch https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02
See above for output from failed command.
Please check the log file manage_externals.log for more details.
INFO : 2018-05-21 13:37:31 : 
ERROR: Failed with output:
    svn: E155007: '/glade/u/home/rgknox/ctsm/components/cism/glimmer-cism' is not a working copy

ERROR: In directory
    /glade/u/home/rgknox/ctsm/components/cism/glimmer-cism
Process did not run successfully; returned status 1:
    svn switch https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02
See above for output from failed command.
Please check the log file manage_externals.log for more details.

```

**Comment by ekluzek** [comment]
@rgknox I've been able to get around this kind of problem by deleting the "components/cism" directory and it's contents "\rm -rf", and then let manage_externals repopulate it with the new version. This is fine as long as you don't have changes under it, which is normally the case.

**Comment by rgknox** [comment]
thanks @ekluzek , that did the trick.

On a side note.  When I ran manage externals, it prompted me for my github user/password 3 times on the fates step.  Seeing how this does not get run often, its not a big deal, but after two attempts I thought it was broken and so I stopped the script.  I then gave it another shot, provided user/pass 3 times, and everything worked.  

Is the 3 prompts unusual?  There may be more people like me who think something is wrong when nothing is wrong, and I'm wondering if a message stating that the passwords are for different parts of the process would prevent future users from wondering what is happening?

**Comment by ekluzek** [comment]
@rgknox, hmmm I don't recall having to enter the password 3 times. But, I think you might have to enter your password each time it has to update a clone. So that means you *could* have to authenticate up to eight times -- once for each clone it has to make.

It does by default tell you what externals it's working on. So you should be able to tell which clone it's authenticating, if you do happen to pay close attention.

**Comment by rgknox** [comment]
from what I could tell, this was all during the cloning of fates.

**Comment by rgknox** [comment]
Updated some tests by removing the finidat requirement.  Without interpolation, its just too hard to keep the finidats up-to-date.  I may add them back in when fates-clm is deprecated.

Ran fates test suite, all RUN pass. I was not planning on comparing this to a baseline, 1 because there is no precedent (I've been using fates-clm as the test suite), and 2 because these changes have very little code touching the model, and they are bound within conditionals for hydro-code.

**Pull request merged**
