### PR TITLE
changing prescribed N and P uptake to 1 in the FATES PRT2 test

### PR DESCRIPTION
**Pull request by rgknox**
### Description of changes

We want to modify the default fates parameter file so that N and P uptake flux is not prescribed if the model is cycling N and P. Having this prescribed uptake active has confused users who are new to exploring N and P cycling.  However, FATES needs prescribed N and P if it is coupling with a land model that is not N or P ready for FATES (such as CLM, which is only  half coupled right now).  This set of changes makes it so that the PRT2 test is forced to have prescribed N and P uptake in FATES.

### Specific notes

Contributors other than yourself, if any:
@jenniferholm

CTSM Issues Fixed (include github issue #): none

Are answers expected to change (and if so in what way)? no, b4b all the way

Any User Interface Changes (namelist or namelist defaults changes)? not really

Does this create a need to change or add documentation? Did you do so? no

Testing performed, if any:

Tests OK, see below.

### CODE REVIEW

**Review by glemieux — APPROVED** [review]

**Review by glemieux — APPROVED** [review]

**Comment by glemieux** [comment]
Per conversation with @rgknox, we're planning on using this to also include the default parameter file update coming with https://github.com/NGEET/fates/pull/1206.

**Review by ekluzek — APPROVED** [review]
Nice and small and tidy, looks great. Nice, use of the autogeneration of FATES parameter files.

**Comment by glemieux** [comment]
Per discussions with @rgknox, we're planning on coordinating this with an default parameter file update that will encompass https://github.com/NGEET/fates/pull/1136 and https://github.com/NGEET/fates/pull/1206.

**Comment by rgknox** [comment]
testing underway:
derecho: /glade/derecho/scratch/rgknox/tests_0813-082243de
Izumi: /scratch/cluster/rgknox/tests_0813-084336iz

**Comment by rgknox** [comment]
Results on derecho from ./cs.status.fails, removing unexpected passes and expected fails. 

```
0813-082243de_gnu: 66 tests
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdDryDepSatPhen BASELINE ctsm5.2.020: DIFF
    FAIL SMS_D.1x1_brazil.I2000Clm60FatesSpCruRsGs.derecho_gnu.clm-FatesColdMeganSatPhen BASELINE ctsm5.2.020: DIFF

```

**Review by samsrabin — APPROVED** [review]

**Pull request merged**
