### PR TITLE
[Fang summer '24 PR 1.1] Fix bugs and develop crop fire modeling

### LINKED ISSUE #2566: bug in crop fire modeling
There is a bug in crop fires in CNFireLi2021Mod.F90 (the fire model developed for CLM5.1 and a possible default one in CESM3). 

``` fortran
 baf_crop(c) = baf_crop(c) + cropfire_a1/secsphr * fhd * fgdp * patch%wtcol(p)
           if( fb * fhd * fgdp * patch%wtcol(p)  >  0._r8)then
              burndate(p)=kda
           end if
should be:
           if( fb * fhd * fgdp * patch%wtcol(p)  >  0._r8)then
 baf_crop(c) = baf_crop(c) + cropfire_a1/secsphr * fhd * fgdp * patch%wtcol(p)
              burndate(p)=kda
           end if
```
The bug causes baf_crop to be incorrectly accumulated, and the global constant cropfire_a1, calibrated using the inverse method, is significantly underestimated. 

Currently, there are three options:
(1) Submit a PR to report the bug. I just conducted the BGC historical run and will obtain the corrected cropfire_a1 and submit the PR tomorrow afternoon.
(2) Submit a PR for the bug, along with developments in crop fire modeling and new crop fire timing inputs, sill in CNFireLi2021Mod (tomorrow afternoon).
(3) Submit the final code of all fire model development (i.e., CNFireLi2024Mod) on Sunday.
Which option do you prefer, and what are the rules for CLM regarding this?

cropfire_a1 was calibrated to match the observed and simulated global totals of crop fire burned area. Despite the incorrect additions of cropfire_a1/secsphr * fhd * fgdp * patch%wtcol(p) when fb=0 ( fhd * fgdp * patch%wtcol(p) always larger than 0 here), the overall impact on the total burned area was mitigated because cropfire_a1 was underestimated. The bug fix will correct these incorrect additions, ensuring that cropfire_a1 is more accurately represented.

### PR DESCRIPTION
**Pull request by samsrabin**
(Supersedes #2576, which I'm replacing so as to put these changes in a new fire module rather than changing `CNFireLi2021Mod.F90`.)

### Description of changes
Copied CNFireLi2021Mod.F90 to new CNFireLi2024Mod.F90. In the latter (original description by @lifang0209 in #2576):
> 1. Fixed the bug described in https://github.com/ESCOMP/CTSM/issues/2566 to avoid incorrect accumulation of baf_crop and ensure that crop fires do not occur during the crop growing season;
> 2. Confined crop fires to periods after harvest and before planting when crop module is active;
> 3. Removed the dependency of baf_crop on fuel availability;
> 4. Improved the modeling of the influence of socio-economic factors on crop burned area
> 5. Recalibrated the cropfire_a1 constant based on GFED5 crop burned area; 
> 6. Modify the declaration of CNFireArea in these F90 files to include the variable crop_inst, declare the variable crop_inst, and import and utilize crop_type from the module CropType.
>
> In addition, the modules CNDriverMod.F90, CNFireLi2014Mod.F90, CNFireLi2016Mod.F90, [CNFireLi2021Mod.F90,] CNFireNoFireMod.F90, FATESFireBase.F90, and FireMethodType.F90 include the subroutine CNFireArea. (6) is implemented in these modules.

The new fire module is not on by default; it requires setting `fire_method` to `li2024gswpfrc`. This will become the default only after #2615 is merged.

### Specific notes

**Contributors other than yourself, if any:** @lifang0209 

**CTSM Issues Fixed (include github issue #):**
- Resolves #2566

**Are answers expected to change (and if so in what way)?** Only when manually setting `fire_method` to `li2024gswpfrc`. Global burned area increases about 30 Mha/yr. Crop fires only occur after harvest and before planting.

**Any User Interface Changes (namelist or namelist defaults changes)?** Yes:
- Adds optional `fire_method` `li2024gswpfrc`.

**Does this create a need to change or add documentation? Did you do so?** New documentation will be needed when `li2024gswpfrc` becomes the default, but not yet.

**Testing performed, if any:**
- @lifang0209 performed historic Bgc and BgcCrop runs to check scientific performance with `li2024gswpfrc`
- `aux_clm` test suite passes bit-for-bit, since by default `li2024gswpfrc` is off.

### CODE REVIEW

**Comment by samsrabin** [comment]
- [ ] Add comment in all other fire modules that `crop_inst` is just being used as a dummy.

**Comment by samsrabin** [comment]
Oh, also:
- [ ] What do you think of the `fire_method` test coverage I added? Specifically, a 65-day 10x15 derecho intel run with each `fire_method`.
- [ ] I had some differences in some tests that were marked as expected failures. There were also two FATES tests that had diffs due to infinity in `FATES_TRANSITION_MATRIX_LULU`. Are those okay?

**Comment by slevis-lmwg** [comment]
I will start with what I know:
The "infinity" result is expected in these FATES tests. Greg has a fix that should be coming in soon.

Regarding test coverage, I could form an opinion if we discussed it, or I'm happy to let others weigh in.

**Comment by samsrabin** [comment]
@slevis-lmwg I think the test coverage is fine for now. We can maybe add more later, perhaps when I make `li2024gswpfrc` the default. Would you mind clicking approve?

**Review by slevis-lmwg — APPROVED** [review]
@samsrabin thank you for working on this.

**Comment by samsrabin** [comment]
`aux_clm` passes. Note that this adds four new tests (2 Derecho, 2 Izumi).

**Pull request merged**
