### PR TITLE
Fates npp fix

### PR DESCRIPTION
**Pull request by rgknox**
### Description of changes

This API change enables fixes to FATES that enabled non-ctsm restarts to work. These fixes are not yet relevant to ctsm because we do not leverage exponentially averaged NPP output boundary conditions from FATES to CTSM when calculating free-living fixation.

### Specific notes

Synchronized with FATES 1114:  https://github.com/NGEET/fates/pull/1114

Contributors other than yourself, if any: @glemieux 

CTSM Issues Fixed (include github issue #): none here, fates issue 1113

Are answers expected to change (and if so in what way)?  No, answers should be b4b

Any User Interface Changes (namelist or namelist defaults changes)? no

Testing performed, if any: regular testing

### CODE REVIEW

**Comment by adrifoster** [comment]
@ekluzek note that this needs to be fast-tracked on the FATES side so we should try to bring this in so we are not behind

**Comment by rgknox** [comment]
testing: /glade/scratch/rgknox/tests_1103-205239ch

**Comment by rgknox** [comment]
cheyenne aux_clm passes against dev149:

```
tests_1104-130505ch>
> ./cs.status.fails 
1104-130505ch_gnu: 54 tests

 
1104-130505ch_int: 116 tests
    PEND ERP_P72x2_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-mimicsFatesCold SHAREDLIB_BUILD (EXPECTED FAILURE)

 
1104-130505ch_nvh: 3 tests
    FAIL SMS_D.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_nvhpc.clm-crop RUN time=26 (EXPECTED FAILURE)
    FAIL SMS.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_nvhpc.clm-crop RUN time=11 (EXPECTED FAILURE)
    FAIL SMS.f45_f45_mg37.I2000Clm51FatesSpRsGs.cheyenne_nvhpc.clm-FatesColdSatPhen RUN time=11 (EXPECTED FAILURE)

 
========================================================================
Non-PASS results for select phases:
TPUTCOMP non-passes: 0
MEMCOMP non-passes: 0
...

**Comment by samsrabin** [comment]
Issue filed as #2236. At standup, this morning, we agreed that @rgknox will go ahead and bring in this PR, noting the issue in ChangeLog.

**Comment by samsrabin** [comment]
The fix to the above is ready: #2237

**Review by ekluzek — APPROVED** [review]

**Pull request merged**
