### PR TITLE
Rename hist fields to track them down more easily

### LINKED ISSUE #2095: Rename MIMICS History Fields
MIMICS history fields should be renamed to make them easier to find.  For example [litter pools are currently written](https://github.com/ESCOMP/CTSM/blob/942de5c248d891cbde945a2c8c27a01af697bc86/src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90#L484) as:
`MET_LIT` & `STR_LIT`, which makes them hard to find on history files.

Seems like naming them `LIT_MET` `LIT_STR` on history files may make more sense?  What do you think of this suggestion @slevis-lmwg ?

### PR DESCRIPTION
**Pull request by slevis-lmwg**
### Description of changes

Renaming history fields to make easier to find in lists, e.g. when using ncview. For example, litter fields like `MET_LIT` and `STR_LIT` will be `LIT_MET` and `LIT_STR`.

### Specific notes

Contributors other than yourself, if any:
@wwieder 

CTSM Issues Fixed (include github issue #):
Fixes #2095 

Are answers expected to change (and if so in what way)?
No, only field names will change.

Testing performed, if any:
I ran the cheyenne test-suite. The FSURDATMOD... test failure is expected according to #2111.

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
I ran the LMWG diag. pkg and found only one plot affected by this PR's changes:
- Set 6 CWD_C, which was CWDC
`https://webext.cgd.ucar.edu/I1850/ERS_Ly3.f10_f10_mg37.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic.C.0814-174352ch_int/lnd/ERS_Ly3.f10_f10_mg37.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic.C.0814-174352ch_int.2_3-ERS_Ly3.f10_f10_mg37.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic.C.0712-190139ch_int.2_3/set6/set6_crbStock_Global.png`

**Comment by samsrabin** [comment]
@slevis-lmwg: Could you send me the path of your failing `FSURDATMODIFYCTSM` test?

**Comment by samsrabin** [comment]
Also: We might want to wait on this until after #2087 is merged, then use `SMS_Ld1.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-SaveHistFieldList` to update the .rst file with all output variables. (Plus a similar test for FATES if it's possible to get these output fields with FATES.)

**Comment by olyson** [comment]
I can change CWDC to CWD_C in the diagnostics package.  Will the corresponding isotope fields change, e.g., C13_CWDC to C13_CWD_C?

**Comment by slevis-lmwg** [comment]
Test-suites IN PROGRESS

**Review by ekluzek — APPROVED** [review]
This looks good to me as far as I can tell.

**Comment by slevis-lmwg** [comment]
> I can change CWDC to CWD_C in the diagnostics package. Will the corresponding isotope fields change, e.g., C13_CWDC to C13_CWD_C?

@olyson yes. I didn't notice because these are inactive currently.

**Comment by olyson** [comment]
@slevis-lmwg , can you try running the diagnostics again and see if you get CWDC/CWD_C plots?

**Comment by slevis-lmwg** [comment]
@olyson, thanks, I think this looks right. The old name worked for the CTRL case. The new one worked for the experiment.

CWDC

CWD_C

**Pull request merged**
