### PR TITLE
Neon modify surfurface dataset 

### PR DESCRIPTION
**Pull request by negin513**
### Description of changes
This PR includes the scripts for modification of the surface dataset for neon sites to address #1429.
Specifically, the following has been addressed in this PR:
1) Update the calculation of `ORGANIC` to use the new field (`CaCO3`) from NEON data. 
For this calculation if `CaCO3` data is available, we first calculate inorganic carbon by:
inorganic carbon = (caco3 /100.0869)*12.0107
Next, we calculate organic carbon by subtracting inorganic carbon from the total carbon:
 [organic carbon = carbon_tot - inorganic carbon]
If the `CaCO3` is not available then the code uses `carbonTot` and `estimatedOC` by NEON. 
 
2) Discussed here (https://github.com/ESCOMP/CTSM/issues/1429#issuecomment-924895184) 
For the Ag sites (KONA and STER), it changes the `PCT_NATVEG`, `PCT_CROP`, and `PCT_NAT_PFT` to avoid the error that we previously had in spin-up:  `surfrd_veg_all ERROR: sum of wt_nat_patch not    1.00000000000000       at nl=  1          sum is:   0.000000000000000E+000 `

3) Discussed here (https://github.com/ESCOMP/CTSM/issues/1429#issuecomment-931648966)
There was a typo previously in the NEON data for ABBY sites caused by mix of sample measurements. Please note that this was updated by hand once data was downloaded from NEON site. 

The following plot shows the results of the above changes in the `ORGANIC` field for all sites comparing it with the original and previous version of the surface dataset:

allsite_organic_sf_profile_v9
 
### Specific notes

Contributors other than yourself, if any: @wwieder  and @danicalombardozzi 

CTSM Issues Fixed (include github issue #): #1429

Are answers expected to change (and if so in what way)? N/A

Any User Interface Changes (namelist or namelist defaults changes)? N/A

### CODE REVIEW

**Comment by wwieder** [comment]
This is fine to come to main, but does it also need to be merged with the NEON updates branch for now so we can get the most up to date NEON code modification?  https://github.com/ESCOMP/CTSM/tree/jedwards/neon_updates

**Comment by wwieder** [comment]
Minor point, but the ORGANIC profiles at MLBS and HEAL look kind of strange. At some point we should double check these for accuracy.  HEAL won't run (too many gaps in datm data), but MLBS may and will certainly look odd with that organic bulge towards the top of the profile.

**Comment by ekluzek** [comment]
We'll keep this as a separate PR, but I'll add it to #1467, and it'll come to CTSM main with that PR.

**Review by jedwards4b — APPROVED** [review]

**Comment by jedwards4b** [comment]
@negin513 I'm confused that there are 57 files changed here and the one file I expect to be changed has conflicts.

**Pull request merged**
