### PR TITLE
Update spinup stability scripts

### PR DESCRIPTION
**Pull request by olyson**
### Description of changes

Update the BGC spinup stability script and add an SP spinup stability script.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #): #1132

Are answers expected to change (and if so in what way)?  Only for spinup stability script output

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
Ran scripts against existing data

### CODE REVIEW

**Review by ekluzek — COMMENTED** [review]
Thanks for making a PR for this @olyson. We want to make contrib scripts really lightweight to bring in, hence I was planning on just approving it. But, alas I have questions. I'm really happy you did testing with this and as the original author you are the best one to evaluate changes to the script.

So my only question is to understand why you added the previous version as "v9" and updated the name of the new one to "_v10"? Are both scripts useful to have at the same time? I wonder if the name shouldn't reflect  the usage difference. Also we should add notes on them to the README file in the tools/contrib directory, especially if the usage is different between them.

**Comment by olyson** [comment]
SpinupStability_SP_v9.ncl is for SP simulations (this wasn't in the repository previously).
SpinupStability_v10.ncl is for BGC simulations.

**Comment by olyson** [comment]
Sorry, I didn't see the README.  I'll update it and push.

**Comment by olyson** [comment]
Ok I've pushed changes to the README and renamed the scripts appropriately.  Thanks for looking at this.

**Review by ekluzek — APPROVED** [review]
OK, thanks for changing that. In the longrun, since there is so much duplication between these scripts, I think we'll want to have a core python module that's shared between them. But, I think it's OK to have two separate scripts for now. We really do need the ability to check both SP and BGC cases, that's a requirement. So thanks for adding that.

Since, this is a tools/contrib thing and you've done the testing/validation, I'm just going to approve as is, and it will be included in the next tag that's made.

**Pull request merged**
