### PR TITLE
Jedwards/io fixes

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
History write changes for compatibility with pio2

### Specific notes
Only write time independent fields in the file once.   In pio2 variables of similar type are aggregated so that all are written to the file at the same time.  When an existing file is reopened and appended the information in the variable description about whether the variable includes the unlimited dimension is lost and so variables with and without this dimension are aggregated for write, this creates an error in pio at write time when it is determined that the variables have different dimension counts. 
This can be considered a pio bug and issue https://github.com/NCAR/ParallelIO/issues/1670 has been opened in that repo. 
This PR applies a workaround so that non-time dependent fields are only written to the file once.    I note that a comment in histFileMod.F90 indicates that these fields should be written each time because they may in fact change values.   This seems like a real problem to me and if this is the case then perhaps they should not be considered time independent.   I have also added pio_syncfile function which is more efficient than closing and immediately reopening a file. 

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #): #1029 #1030 

Are answers expected to change (and if so in what way)?

Any User Interface Changes (namelist or namelist defaults changes)?

Testing performed, if any:
The following tests were run with both pio1 and pio2:
ERS_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.cheyenne_intel 
ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesGs.cheyenne_gnu.clm-FatesColdDef

(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by ekluzek** [comment]
I was concerned about @jedwards4b comment about time constant variables changing. I found the place in the code that I think he is referring to, and it's from 6 to 8 years ago, and I would say it's incorrect. Here it is...

``` fortran
       ! Most of this is constant and only needs to be done on tape(t)%ntimes=1
       ! But, some may change for dynamic PATCH mode for example

       if (ldomain%isgrid2d) then
          call ncd_io(varname='lon', data=lon1d, ncid=nfid(t), flag='write')
          call ncd_io(varname='lat', data=lat1d, ncid=nfid(t), flag='write')
       else
          call ncd_io(varname='lon', data=ldomain%lonc, dim1name=grlnd, ncid=nfid(t), flag='write')
          call ncd_io(varname='lat', data=ldomain%latc, dim1name=grlnd, ncid=nfid(t), flag='write')
       end if
       call ncd_io(varname='area'    , data=ldomain%area, dim1name=grlnd, ncid=nfid(t), flag='write')
       call ncd_io(varname='landfrac', data=ldomain%frac, dim1name=grlnd, ncid=nfid(t), flag='write')
       call ncd_io(varname='landmask', data=ldomain%mask, dim1name=grlnd, ncid=nfid(t), flag='write')
       call ncd_io(varname='pftmask' , data=ldomain%pftm, dim1name=grlnd, ncid=nfid(t), flag='write')
       call ncd_io(varname='nbedrock' , data=grc%nbedrock, dim1name=grlnd, ncid=nfid(t), flag='write')
```

None, of those variables can change. pftmask is the mask for PFT's, which can't change in time even though PFT's themselves change. So the comment just looks incorrect to me.

**Comment by jedwards4b** [comment]
Yes, that is the comment I was referring to.  Thanks @ekluzek.   I am running ctsm tests on cheyenne and izumi now.

**Comment by billsacks** [comment]
@jedwards4b and @ekluzek - I have a few follow-up questions on where things stand with this PR:

1. Were you able to run all of the aux_clm tests with these changes? If so, did you run them with the defaults for PIO (so using PIO1) or with PIO2, or both? If with PIO2, did you include the  fix for https://github.com/NCAR/ParallelIO/issues/1670? And what was the status of this testing?

2. It looks like, with the latest commit, you have gone back to calling `htape_timeconst` every time because (contrary to the name of this subroutine) some of the things in here aren't time-constant. Does that work, or do we need to add some logic to only do those writes once?

3. It looks like the main behavior change in this PR is now that the fields in `hfields_1dinfo` are just written once, in the first time, rather than being rewritten each time. It looks like this will potentially change behavior in the (probably rare, but possible) case where there is a multi-time 1-d history file that spans the year boundary: on master, it looks like this would give the subgrid areas in the last time, but with this PR, it would give the subgrid areas in the first time. This may not be a big deal, but it does feel less self-consistent, since the time on the file gives the ending time yet these fields would now apply to the starting time. I'm wondering:

    a. Is this change actually still needed, given that it looks like you have fixed the underlying pio2 issue?

    b. If this change is still needed, perhaps @ekluzek or I should look into whether we can change the logic so that these fields are only written in the last time, rather than the logic in this PR where they are written in the first time. (The main potential gotcha I see with that is that it means the fields would be undefined on the file until the last time is written. In particular, would this be a problem for a file that spans a restart?)

**Comment by jedwards4b** [comment]
1. All of the tests ran on izumi with pio2.   Only one failure 
0724-153311iz_nag: 35 tests
    FAIL ERS_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.izumi_nag.clm-monthly RUN time=1293
As far as I can tell this fail is not associated with the code change

On cheyenne I had the following 
 ./cs.status.fails 
0727-085945ch_gnu: 46 tests
    FAIL SMS_Ld1.nldas2_rnldas2_mnldas2.I2000Ctsm50NwpSpNldasGs.cheyenne_gnu.clm-default NLCOMP

 
0727-085945ch_int: 162 tests
    FAIL DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv RUN time=1224
    PEND DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv COMPARE_base_da
    FAIL ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic COMPARE_base_rest
    FAIL ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic BASELINE ctsm1.0.dev105: DIFF
    FAIL SMS.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.ISSP585Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode RUN time=1223

 
========================================================================
Non-PASS results for select phases:
TPUTCOMP non-passes: 31
MEMCOMP non-passes: 16

2.  I did change it to call at each write again so that the time variables are written, but I changed so that only the time dependent variables are written.

3. If these fields are time dependent then you should change so that they are written for each time, if they are not time dependent then it doesn't matter when you write them.
 a. I haven't brought the new version of pio into cime yet. 
 b. Again if you are changing the time that a time-independent field is written and expecting a different result then you have a problem and you should reconsider the nature of these variables.

**Comment by billsacks** [comment]
@jedwards4b thanks a lot for your replies. Some follow-ups below:

(1) Test results:

*Remaining issues*

- [ ] `FAIL ERS_Ly5_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropQianGs.izumi_nag.clm-monthly RUN time=1293`: this is issue #1030 . So I guess your changes here do not resolve that issue, and some other fixes – either in CTSM or in PIO2 – are needed for this case.

- [ ] `ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic`: There seems to be a problem in the writing of `time_bnds` on the cpl aux hist file (`ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic.C.0727-085945ch_int.cpl.hl2x1yr_glc.0003-01-01-00000.nc.base` and `ERS_Ly3.f10_f10_musgs.I1850Clm50BgcCropCmip6.cheyenne_intel.clm-basic.C.0727-085945ch_int.cpl.hl2x1yr_glc.0003-01-01-00000.nc.rest`): in your runs, time_bnds are `730, 0.999999999999535` and `730, 0`, whereas in a recent run from CTSM master (with pio1), time_bnds is `730, 1095`, as expected. This should have nothing to do with the CTSM changes, but maybe is something else that isn't working right with pio2 (possibly due to issues in the mct driver code, not necessarily pio2 issues per se).

*No need to worry about these*

- `FAIL DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv RUN time=1224`: looks like it just ran out of wallclock time, maybe due to system slowness (so no need to worry about this one)

- `SMS.ne0ARCTICGRISne30x8_ne0ARCTICGRISne30x8_mt12.ISSP585Clm50BgcCrop.cheyenne_intel.clm-clm50cam6LndTuningMode`: this seems to be a new test, which looks like it failed for @ekluzek , too.

(2) `htape_timeconst`: Thanks; no more follow-ups needed here.

(3) Behavior change in `hfields_1dinfo`: I understand and appreciate your points here, but given how overwhelmed we are right now with a backlog of issues, I'd prefer to avoid this change if it isn't actually needed, since it is likely to require some additional discussion and/or code changes. My understanding is that, once we can point to a version of cime with updated pio2, the change you made here won't be necessary; is that correct?

- [ ] I think we should then back out this change to `hfields_1dinfo`, if it isn't actually needed.

**Comment by jedwards4b** [comment]
Superceeded by #1095

**Pull request closed without merging**
