### PR TITLE
add support for 64bit_data, fix fillvalues

### PR DESCRIPTION
**Pull request by jedwards4b**
Add support for pio_64bit_data format (already defined in namelist but not used) 
Fix issues with fill values.

### CODE REVIEW

**Comment by ekluzek** [comment]
This includes a fix for #240.

**Comment by ekluzek** [comment]
This change shouldn't change answers so is planned to go into clm4_5_18_r276.

**Comment by jedwards4b** [comment]
Can we get this into cesm2 alpha10 please?

**Comment by ekluzek** [comment]
Yes, it's planned for the next CLM tag, which is now clm5.0.dev002.

**Comment by ekluzek** [comment]
The testing for this has happened on my importfixes branch.

**Pull request merged**
