### PR TITLE
black reformat python files for consistancy across cesm

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Black reformats buildlib and buildnml 
### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)? NO

Any User Interface Changes (namelist or namelist defaults changes)? NO

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by ekluzek** [comment]
I support using black for our python code. There's probably other code that we should run through black as well. We do run the python code under the python directory through black, but other python codes should as well.

**Comment by ekluzek** [comment]
@jedwards4b what version of black did you use for this PR?

**Comment by jedwards4b** [comment]
black --version
black, 22.3.0

**Comment by ekluzek** [comment]
We talked about their briefly yesterday. We are supportive of this. The version of black we are using right now is the same as used here.

I do think we should regularly test buildlib and buildnml through black. That can be added in our python directory testing. Those tests don't run it through black, just test and it and show the user if it fails. We also have a black action and it could be extended to also check these two files.

I'll bring this in with some other simple bit-for-bit type changes and we'll schedule it to come in...

**Pull request merged**
