### PR TITLE
change needed for the addition of a dglc component in cdeps

### PR DESCRIPTION
**Pull request by mvertens**
### Description of changes
change needed for the addition of a dglc component in cdeps

### Specific notes
This minor change to buildnml is needed in order to support the addition of dglc which will replace CISM running in noevolve mode.
This will enable having many of the current CTSM tests that use SGLC move to using DGLC%NOEVOLVE.

Contributors other than yourself, if any: None

CTSM Issues Fixed: None

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
Ran a test case with 
compset 1850_DATM%GSWP3v1_CLM50%SP_SICE_SOCN_SROF_DGLC%NOEVOLVE_SWAV  and resolution  f10_f10_ais8gris4_mg37 
and compared to 
compset 1850_DATM%GSWP3v1_CLM50%SP_SICE_SOCN_SROF_CISM%NOEVOLVE_SWAV  and resolution  f10_f10_ais8gris4_mg37

### CODE REVIEW

**Comment by ekluzek** [comment]
@mvertens thanks so much for working on this and bringing this in. I really like the idea of having a data GLC model to take the place of CISM NO-EVOLVE mode. This also resolves #2222 for us which is really important.

But, I have some questions for you on this:

- It looks like this is a work in progress correct? How close is this to being considered done by you?
- Will it require a CDEPS update to bring in?
- Right now this won't change answers for anything existing correct?

Since this is adding new capability and is fairly straight forward (and provided it doesn't change answers otherwise)-- I think I should rebase this to the b4b-dev branch. So I'll do that once you verify Doing that means it's easier to get in sooner. I'll work with you to do that once I hear more about this from the questions above.

I'm also going to make an issue about adding DGLC to CTSM which will allow us to close #2222 and track everything that will need to be done for this change. Again I'll wait until hearing and then I'll have you add anything there that I'm missing after the issue is started...

**Comment by ekluzek** [comment]
Thanks for that update @billsacks. So there is only one more thing needed here and that is an update for CISM (once that is done). Other things will be done in future PR's and we can document those in the issue I'll open.

So things needed for this:

- [ ] Create an issue that documents all the things needed for DGLC (Erik will do this)
- [ ] Update CISM so it uses GLC_USE_ANTARCTICA (@Katetc and @billsacks will do this)
- [ ] Rebase this to b4b-dev (Erik can do this)

**Review by ekluzek — APPROVED** [review]
This is really great glad to see this coming in.

The code changes right now are very simple, so not much to review. But, having both DGLC and CISM use the same XML variable for similar behavior is a nice improvement.

**Comment by ekluzek** [comment]
@billsacks can you comment on how much of our testing should change from using the stub-glacier model to DGLC? Are there reasons outside of fully coupled B1850 compsets that we should prefer running with DGLC over SGLC? Scientifically it's obviously an update to use DGLC rather than a stub, but in what ways will this matter for CTSM simulations?

**Comment by wwieder** [comment]
Glad to see this can come in on b4b_dev.  Is that we want to get in this week, or can it wait another 2 weeks? I guess the logistics are a question for @billsacks and @ekluzek .  The urgency is more a question for @mvertens and @Katetc?

**Comment by billsacks** [comment]
> can you comment on how much of our testing should change from using the stub-glacier model to DGLC? Are there reasons outside of fully coupled B1850 compsets that we should prefer running with DGLC over SGLC? Scientifically it's obviously an update to use DGLC rather than a stub, but in what ways will this matter for CTSM simulations?

I'll comment on that over in #1136 

> Glad to see this can come in on b4b_dev. Is that we want to get in this week, or can it wait another 2 weeks? I guess the logistics are a question for @billsacks and @ekluzek . The urgency is more a question for @mvertens and @Katetc?

It would be great to get this in this week, since this is required for the CDEPS change that we want to merge.

**Comment by ekluzek** [comment]
OK in that case I've rebased it to b4b-dev and as long as we get the CISM tag in by Wednesday morning we can bring it into b4b-dev, which will then go to master on Thursday.

**Comment by ekluzek** [comment]
Testing for aux_clm looks as expected. So merging.

**Pull request merged**
