### PR TITLE
Reduce redundancy; make interfaces more similar between tools; focusing here on fsurdat_modifier and subset_data

### PR DESCRIPTION
**Pull request by slevisconsulting**
### Description of changes
Details in #1662 

### Specific notes
Starting by replacing zero_nonveg option with include_nonveg

Contributors other than yourself, if any:
@ekluzek @negin513 @adrifoster 

CTSM Issues Fixed (include github issue #):
#1662 

Are answers expected to change (and if so in what way)?
No

Any User Interface Changes (namelist or namelist defaults changes)?
Making interfaces more similar between tools, e.g. replacing zero_nonveg with include_nonveg

Testing performed, if any:
This far...
make lint: PASS
make test: OK (pre-existing errors in `test_buildSetup_userDefinedMachine_allInfo` and `test_buildSetup_userDefinedMachine_minimalInfo`

### CODE REVIEW

**Comment by slevisconsulting** [comment]
add to README:
```
module unload python
module load conda
./manage_python_env
conda activate ctsm_py
```

**Comment by ekluzek** [comment]
As with the other PR make sure 51c102c5df2e0ef971b5f8eeeb477567899af63a is added to the .git-blame-ignore-revs file.

**Review by ekluzek — APPROVED** [review]
This is a nice update to make scripts more similar to each other.

**Review by ekluzek — CHANGES_REQUESTED** [review]
OK, looking at #1667 I do now think that dom_plant should be changed to dom_pft since the meaning in subset_data was changed. So that's the one change I see.

**Comment by slevisconsulting** [comment]
python testing PASS
pymods testing PASS

**Comment by slevisconsulting** [comment]
This PR should probably get merged before #1677.
We'll see whether I can address @ekluzek's last few comments in #1677 to have it ready right after...

**Review by ekluzek — APPROVED** [review]

**Comment by ekluzek** [comment]
OK, awesome, you've done everything I see. I'm not able to tie this off today, but should be Wednesday night or Thursday.

**Comment by ekluzek** [comment]
@slevisconsulting on the pylint issue, make sure you setup the ctsm_py environment and activate it, and that the error is seen under that environment. pylint is very sensitive to the exact version being used. If we see it in that environment we should fix it.

**Comment by wwieder** [comment]
@ekluzek aren't you on PTO...?

**Comment by slevisconsulting** [comment]
> @slevisconsulting on the pylint issue, make sure you setup the ctsm_py environment and activate it, and that the error is seen under that environment. pylint is very sensitive to the exact version being used. If we see it in that environment we should fix it.

Good news @ekluzek. As you expected, once I executed
`conda activate ctsm_py`
the pylint complaints disappeared!

Thanks!

**Pull request merged**
