### PR TITLE
always use the only modifier

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Add only modifier to use statements for esmf and nuopc 
### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed: #1846 

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)?

Testing performed, if any: 
SMS_Ld3.f09_g17.I1850Clm50BgcNoAnthro.gust_cray.clm-decStart1851_noinitial 

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Review by billsacks — APPROVED** [review]
Thanks a lot for this @jedwards4b and sorry again about my confusion in the issue.

**Comment by ekluzek** [comment]
@jedwards4b thanks for this contribution. I'll be bringing it in.

I did notice that there are other uses of "use ESMF" that leave off the "only clause". Do you think that's an issue that we should fix? There are now no instances of "use NUOPC" without the "only clause", which is maybe the thing that the CCE compiler was having trouble with. But, I'm wondering if we should do the same for some of these other cases that in files:

cpl/lilac/lnd_comp_esmf.F90
cpl/lilac/lnd_comp_shr.F90
cpl/lilac/lnd_import_export.F90
cpl/lilac/lnd_shr_methods.F90
cpl/mct/lnd_comp_mct.F90.  <--- the MCT version doesn't matter
cpl/nuopc/lnd_comp_shr.F90
cpl/share_esmf/ch4FInundatedStreamType.F90
cpl/share_esmf/FireDataBaseType.F90
cpl/share_esmf/laiStreamMod.F90
cpl/share_esmf/lnd_set_decomp_and_domain.F90
cpl/share_esmf/ndepStreamMod.F90
cpl/share_esmf/SoilMoistureStreamMod.F90
cpl/share_esmf/UrbanTimeVarType.F90
unit_test_shr/unittestTimeManagerMod.F90 <-- as a unit test this doesn't matter
utils/clm_time_manager.F90

I suspect we likely want to fix this for LILAC, and the streams files are probably only using ESMF_LogFoundError and ESMF_Finalize, so they would be easy to take care of. The time manager would be pretty restricted to ESMF time objects and methods so would be fairly easy to take care of.

**Comment by ekluzek** [comment]
I ran the clm_short testlist on cheyenne, just to make sure we didn't see anything odd with this before cheyenne goes down this next week.

ERP_D_P36x2_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_gnu.clm-default			
ERP_D_P36x2_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default			
ERS_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_gnu.clm-default			
ERS_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default			
SMS_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.cheyenne_intel.clm-default

**Comment by jedwards4b** [comment]
@ekluzek I feel strongly that always using the only clause will reduce errors and ease debugging.

**Review by ekluzek — APPROVED** [review]

**Pull request merged**
