### PR TITLE
Get FATES working for NEON

### LINKED ISSUE #1609: Need to get FATES working for NEON
We need to make it easy to run with FATES for a NEON site. Currently there isn't a compset alias for FATES with tower data. So we need to add that. Second, the user mods for FATES currently assume that BGC is active. So for example ndep and fire data are set in the namelist, things that FATES normally either doesn't use or only under certain conditions.

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

Proposal for changes to get FATES working for NEON

### Specific notes

Contributors other than yourself, if any: Whole team in discussing this

CTSM Issues Fixed (include github issue #):
  Fixes #1609

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)?
  Added new use-cases: 2018-PD_NEON_transient, PD_control, 2018_control

Testing performed, if any:
   So far just the build-namelist testing

### CODE REVIEW

**Comment by ekluzek** [comment]
At the NEON meeting @adrifoster pointed out that we'll likely need a different list of output history fields for FATES than BGC (and possibly SP as well). I could do that in the user-mod directory, with bash logic so that we don't have to create more user-mod directories. The other way would be to possibly put it in the use case, or more embedded into build-namelist (probably namelist_defaults_ctsm.xml).

**Comment by wwieder** [comment]
yep, good idea here Erik we're using user_mod_dirs to set this up for the NEON case, but a more general way of defining the default history file output for different configurations (SP/BGC/FATES) would be helpful.

**Comment by wwieder** [comment]
@ekluzek and @adrifoster we still may need some documentation, but is this issue resolved?

**Comment by adrifoster** [comment]
> @ekluzek and @adrifoster we still may need some documentation, but is this issue resolved?

I guess it depends on our definition of done.... we still don't have anything for the crop sites, which is maybe fine. I am working on a solution to update the surface datasets... and `run_neon` doesn't work for FATES.... but you *can* run FATES at most of the NEON sites.

**Pull request closed without merging**
