### PR TITLE
Uncomment fates_hdim_levleaf dimension

### LINKED ISSUE #1485: Forthcoming FATES satellite phenology ERS test fails
### Brief summary of bug

In upcoming PR #1182, I've added two exact restart (ERS) regression tests for checking the FATES nocomp and sp modes.  Both tests run, but the sp mode fail the `COMPARE_base_rest` check.

### General bug information

**CTSM version you are using:** [output of `git describe`]: ctsm5.1.dev054 (merge into PR branch)

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]: No

**Configurations affected:** [Fill this in if known.]

### Details of bug

As this is a new test the scienctific 'baseline' that we have been comparing against is: `/glade/scratch/rfisher/archive/seb_CLM5-SPfates-def_rewindtest0`

We've tried a number of modifications to the code to develop a hypothesis on what might be at issue here.  The following result in a passing restart check, although they change science relative to expected values, but may be helpful in refining the direction of the investigation:

1. If the [SatellitePhenology input filter](https://github.com/rosiealice/ctsm/blob/a12d02ff3dd8031ee4da5ca72e7fea09d45e2cd4/src/main/clm_driver.F90#L1018) is reverted to match the dev054 master use of the `nolakep` filter
2. If `hlm_sp_tlai` is hardcoded to `1.0` in the `dynamics_driv` procedure [here](https://github.com/rosiealice/ctsm/blob/a12d02ff3dd8031ee4da5ca72e7fea09d45e2cd4/src/utils/clmfates_interfaceMod.F90#L858)

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

### Important output or errors that show the problem

An example of the RMS values:

```
 RMS GPP                              1.2990E-15            NORMALIZED  9.3304E-11
 RMS GPP                              2.1805E-15            NORMALIZED  1.5623E-10
 RMS NPP                              2.9692E-15            NORMALIZED  2.3944E-10
 RMS NPP_BY_AGE                       1.1223E-15            NORMALIZED  6.3350E-10
 RMS GPP                              4.2219E-15            NORMALIZED  2.9210E-10
 RMS NPP                              2.9692E-15            NORMALIZED  2.3321E-10
 RMS NPP_BY_AGE                       1.1223E-15            NORMALIZED  6.1702E-10
 RMS GPP                              8.6293E-15            NORMALIZED  5.8525E-10
 RMS NPP                              8.9077E-15            NORMALIZED  6.8931E-10
 RMS NPP_BY_AGE                       3.3668E-15            NORMALIZED  1.8237E-09
 RMS GPP                              1.3454E-14            NORMALIZED  9.1870E-10
 RMS NEP                              2.6937E-14            NORMALIZED  1.5189E-09
 RMS NPP                              1.4846E-14            NORMALIZED  1.1480E-09
 RMS NPP_BY_AGE                       5.6113E-15            NORMALIZED  3.0373E-09
 RMS GPP                              5.7336E-14            NORMALIZED  3.9440E-09
 RMS NEP                              6.8923E-14            NORMALIZED  3.9319E-09
 RMS NPP                              5.6746E-14            NORMALIZED  4.4236E-09
 RMS NPP_BY_AGE                       2.1448E-14            NORMALIZED  1.1704E-08
 RMS GPP                              7.8817E-14            NORMALIZED  5.3616E-09
 RMS NEP                              1.0230E-13            NORMALIZED  5.7934E-09
 RMS NPP                              7.9399E-14            NORMALIZED  6.1155E-09
 RMS NPP_BY_AGE                       3.0010E-14            NORMALIZED  1.6180E-08
 RMS BTRAN                            4.1001E-08            NORMALIZED  2.0020E-07
 RMS GPP                              6.2544E-14            NORMALIZED  4.2769E-09
 RMS H2OSOI                           8.6843E-09            NORMALIZED  5.3278E-08
 RMS HR                               3.7262E-12            NORMALIZED  2.6965E-06
 RMS NEP                              4.8798E-12            NORMALIZED  2.7815E-07
 RMS NPP                              8.8459E-14            NORMALIZED  6.8576E-09
 RMS NPP_BY_AGE                       3.3434E-14            NORMALIZED  1.8143E-08
 RMS T_SCALAR                         1.9021E-07            NORMALIZED  5.1479E-07
 RMS BTRAN                            6.8671E-07            NORMALIZED  3.3903E-06
 RMS GPP                              1.2209E-13            NORMALIZED  8.5802E-09
 RMS H2OSOI                           1.9069E-07            NORMALIZED  1.1676E-06
 RMS HR                               4.9060E-11            NORMALIZED  3.5217E-05
 RMS NEP                              6.0937E-11            NORMALIZED  3.5792E-06
 RMS NPP                              1.3527E-12            NORMALIZED  1.0798E-07
 RMS NPP_BY_AGE                       5.1125E-13            NORMALIZED  2.8570E-07
 RMS TOTSOMC                          2.2544E-06            NORMALIZED  3.7139E-09
 RMS T_SCALAR                         2.8031E-06            NORMALIZED  7.5689E-06
```

Screenshot of the comparison(right) between base (left) and rest(middle) output files for `GPP`:
Screenshot from 2021-09-13 13-52-27

It should be noted that `TLAI` is reported in the output and passes the restart.

### LINKED ISSUE #1561: Uncomment fates_levleaf fields
In ctsm5.1.dev062 I brought in PR #1540, but in order to not have to include a new FATES tag I commented out two lines for the fates_levleaf dimension in this commit...

5e1adf8a909386fbef33c9eacef725a992588df4

We didn't want to bring in a new FATES tag since we didn't have one that just did that one change. And we needed answers for FATES to be identical, since we were already bringing in answer changes going to NUOPC as the new driver.

@glemieux @rgknox let me know if you have any feedback on this. @adrifoster

### PR DESCRIPTION
**Pull request by ekluzek**
### Description of changes

This reverts commit 5e1adf8a909386fbef33c9eacef725a992588df4.

And hence fixed #1561 by uncommenting fates_levleaf dimension.

This PR corresponds to the fates PR https://github.com/NGEET/fates/pull/752.

### Specific notes

Contributors other than yourself, if any: @glemieux @adrifoster 

CTSM Issues Fixed (include github issue #):
  Fixes #1561
  Fixes #1485

Are answers expected to change (and if so in what way)? FATES only for field list, one test has roundoff level differences
 SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdDefHydro

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any: None so far, will run regular tests
  Test should be identical. FATES tests should only be different due to field list.

### CODE REVIEW

**Comment by ekluzek** [comment]
Since this requires a FATES PR that hasn't come in yet, we will hold off on this and bring it in with another FATES update.

**Comment by glemieux** [comment]
Izumi test results look good.  All expected `aux_clm` and `fates` tests all pass b4b.  Folder locations:
`/scratch/cluster/glemieux/ctsm-tests/tests_vai-bin-aux_clm`
`/scratch/cluster/glemieux/ctsm-tests/tests_vai-bin-fates`

**Comment by glemieux** [comment]
> I'm seeing a failure for `SMS_D_Ld9.f09_g17.I1850Clm50BgcNoAnthro.cheyenne_intel.clm-decStart1851_noinitial` which has a pretty large stack trace that I won't reproduce here. It looks like it might be an issue with ESMF?

Upon re-submission the test passes b4b.

**Comment by glemieux** [comment]
Re-running tests as we decided to integrate the fates ers sp mode fix (https://github.com/NGEET/fates/pull/821) prior to integrating the this PR.  

Izumi: All expected `aux_clm` tests pass B4B: `/scratch/cluster/glemieux/ctsm-tests/tests_vai-bin-aux_clm-ersfix`

Cheyenne: 
All expected `aux_clm` tests pass B4B, with the exception of one fates hydro testmod DIFF, which has been deemed acceptable per https://github.com/NGEET/fates/pull/752#issuecomment-985086821.  There was a bit of a 'hiccup' that seemed to cause a few fine resolution grids to hit the wall clock time, but upon re-submission, they all complete with an expected run time.  My suspicion that it was a temporary machine issue is given that the testmods affected were pretty disparate in setup aside from the grid size.
Test location: /glade/u/home/glemieux/scratch/ctsm-tests/tests_vaibin-ctsmdev070-auxclm-ersfix

**Pull request merged**
