### PR TITLE
compatabiilty with FATES v2 nutrient API

### PR DESCRIPTION
**Pull request by rgknox**
### Description of changes

This set of changes only addresses changes to the history API and updates to the parameter file, to enable compatability with a new version of FATES.  This set of changes does not add coupled N cycling with FATES (that will follow this).

This set of changes is synchronized with: https://github.com/NGEET/fates/pull/880

### Specific notes

Further modifications to this branch are necessary. 1) The associated FATES side PR is not currently next in queue, and an update to the default parameter file will precede the change included here.  2) We are debating the importance of having mapping variables in the history file for multiplexed variables. This PR introduces a new multiplexed fates dimension that is canopy-layer x size-class x pft (CLSZPF).  We will probably, but not necessarily add mapping variables that connect this multiplexed dimension to the 3 component dimensions.

Contributors other than yourself, if any:

Many, see  https://github.com/NGEET/fates/pull/880

CTSM Issues Fixed (include github issue #):

none

Are answers expected to change (and if so in what way)?

Changes are only expected in fates tests where fates_parteh_mode = 2.

Any User Interface Changes (namelist or namelist defaults changes)?  There may be updates to the list of variables included in testing.

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by rgknox** [comment]
Initial tests are showing differences compared to base in the FATES_LITTER_OUT and FATES_CBALANCE_ERROR, no other differences detected so far.  Here is how the fates_litter_out diagnostic is constructed:

https://github.com/NGEET/fates/blob/main/main/FatesHistoryInterfaceMod.F90#L3485-L3490

In this PR, effluxes from the plant (due to excess carbon) are added to the litter fragmentation flux, where in main they were not.  This is also reflected in the error term, as they have the exact same difference as the fragmentation flux. 
 These are typically very small, and from the test results, are very small. Honestly, I forget why I did this (but Ryan from the past may have had a good reason!).  I think its because it made it cleaner to track carbon conservation between the host and fates.

**Comment by rgknox** [comment]
aux_clm tests seem nominal, nlcomps are expected and diffs with base are expected with fates tests:
/scratch/cluster/rgknox/tests_1201-122133iz
/glade/scratch/rgknox/tests_1201-121507ch

**Review by ekluzek — COMMENTED** [review]
The changes here are really straightforward, and not much to say about it. The real changes are likely inside of FATES.

The only nitpick I saw was that there's some whitespace at the end of lines. This is the sort of thing that we could use a pre-commit filter to help us with.

**Comment by ekluzek** [comment]
I did my normal double checking, the 21 cheyenne and 10 izumi Fates tests passed, with expected answer changes.

**Pull request merged**
