### PR TITLE
Fix error in HumanIndexMod (QSat_2 subroutine)

### PR DESCRIPTION
**Pull request by olyson**
### Description of changes

See Issue #1250 
### Specific notes

See Issue #1250 

Contributors other than yourself, if any: J. Buzan

CTSM Issues Fixed (include github issue #): #1250

Are answers expected to change (and if so in what way)? See issue #1250 

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
Ran small subset of tests from aux_clm to demonstrate default model configurations are bfb.

### CODE REVIEW

**Review by ekluzek — APPROVED** [review]
@olyson thanks for turning this into a PR. There is of course not much to review. So looks fine. 

Since, it will cause an apparent change in answers, we'll have to figure out about how to schedule it in.

**Comment by billsacks** [comment]
I'm planning to make a simple bfb tag in the next few days. I'll fold this in there (since this is nearly bfb).

**Comment by billsacks** [comment]
@olyson @ekluzek the humanstress unit tests fail with this change. So I'm backing it out of my upcoming tag. I haven't investigated to determine whether the unit tests are uncovering a true issue or if the tests themselves now need to be updated. I figured the two of you, along with J. Buzan, are more familiar with this so would be in a better position to debug.

The failure looks like this:

```
11/43 Test #11: humanstress ......................Child aborted***Exception:   0.38 sec
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
test_humanstress_  0000000001263104  Unknown               Unknown  Unknown
libpthread.so.0    00002B30DDB4DB00  Unknown               Unknown  Unknown
test_humanstress_  00000000012456B9  Unknown               Unknown  Unknown
test_humanstress_  000000000114E846  humanindexmod_mp_        1369  HumanIndexMod.F90
test_humanstress_  000000000114DA83  humanindexmod_mp_         961  HumanIndexMod.F90
test_humanstress_  00000000004047BA  test_humanstress_          86  test_humanstress.pf
test_humanstress_  000000000110B93D  testmethod_mod_mp          87  TestMethod.F90
test_humanstress_  0000000001109FED  testcase_mod_mp_r         149  TestCase.F90
test_humanstress_  000000000110A2D4  testcase_mod_mp_r         159  TestCase.F90
test_humanstress_  0000000001119CF0  testresult_mod_mp         234  TestResult.F90
test_humanstress_  0000000001109C36  testcase_modrun_m         134  TestCase.F90
test_humanstress_  000000000110979D  testcase_mod_mp_r         121  TestCase.F90
test_humanstress_  000000000112B514  testsuite_mod_mp_         114  TestSuite.F90
test_humanstress_  000000000112B514  testsuite_mod_mp_         114  TestSuite.F90
test_humanstress_  00000000011278BA  testrunner_mod_mp         100  TestRunner.F90
test_humanstress_  00000000004097B3  MAIN__                    226  driver.F90
test_humanstress_  0000000000403C62  Unknown               Unknown  Unknown
libc.so.6          00002B30DE27B6E5  __libc_start_main     Unknown  Unknown
test_humanstress_  0000000000403B69  Unknown               Unknown  Unknown
..
```

This passes with gnu on my mac, but fails with intel on cheyenne.

This is from running `../cime/scripts/fortran_unit_testing/run_tests.py --build-dir unit_tests.temp` from the `src` directory.

**Comment by olyson** [comment]
Is there a driver for this test that I can look at and understand how to see what the inputs and outputs of this unit test are?

**Comment by billsacks** [comment]
https://github.com/escomp/ctsm/blob/master/src/biogeophys/test/HumanStress_test/test_humanstress.pf#L43

I think this was written by @ekluzek if you have questions about it.

**Comment by ekluzek** [comment]
Yes, it might be good for @olyson and I to work on it together. And actually it might be good for me to just work on it for a little bit, as I might be able to fix it without spending a lot of time. If I get stuck or it starts taking more time then we'll need both of us to look at it. On the other hand, if you want to spend some time on it I don't object. It would be good for you to understand how these unit tests work, and especially this one in particular.

**Comment by dlawrenncar** [comment]
Would be good if Keith could take a look.  Erik has a lot on his plate that
is in critical path.

**Comment by olyson** [comment]
Yes, I'll look at it and I'll get J. Buzan involved if necessary.

**Comment by olyson** [comment]
The algorithm is failing at temperature = 53C, relative humidity = 100% (the maximum temperature and relative humidity combination specified by the unit test).
This would yield a wet bulb temperature of about 53C.  Per J. Buzan, the algorithm is actually only valid for wet bulb temperatures at 50C or below.  The unit testing passed previously but was likely borderline. 

This line in HumanIndexMod.F90:

if ( wb_temp > 100._r8 ) exit

should be:

if ( wb_temp > 50._r8 ) exit

so that the iteration is exited and then wb_it = wb_temp (wet bulb temperature is set to 50C).

I think it's fine to leave the unit test as is, since it exercises the statement above when wet bulb is above 50C.

I've pushed this change to my branch:

https://github.com/olyson/ctsm/tree/fixhumanindexmod

**Pull request merged**
