### PR TITLE
Update manage_externals to v1.0.1

### PR DESCRIPTION
**Pull request by ekluzek**
Update manage_externals to manic-v1.0.1

### CODE REVIEW

**Comment by bandre-ucar** [comment]
The recommended procedure to update manage_externals is:

https://github.com/NCAR/manage_externals/wiki#including-manage_externals-in-other-repositories

I think this PR is generally ok: it looks like you used the subtrees and the manage_externals tests pass. But, from the commit id's I think you pulled in the annotated tag which resolves to commit 81ccf92, rather than the actual commit, 0527869d26. Is that correct?

The log shows:

```
Squashed 'manage_externals/' changes from 5fc8709..81ccf92

0527869 Update readme
1ae8c84 Merge bugfix branch for stale subexternals into master.
b0c16d7 Bugfix: stale sub-externals after checkout.
30a4e44 Finish implementing system test for mixed-use externals
ac7ff96 Update mixed-use test repo.
bfda7b9 Bugfix: regexp for determining git tracking branches

git-subtree-dir: manage_externals
git-subtree-split: 81ccf92e8c4da272121fcc96902021be9e7a7b1f
Commit:
e11b68bbf4880d8d7a7e5e66f5201a32eada2832 [e11b68bb]
Parents:
c843f07448
Author:
Erik Kluzek <erik@ucar.edu>
Date:
March 30, 2018 at 4:16:35 PM MDT
```

But it should show:

```
Squashed 'manage_externals/' changes from 5fc8709a..0527869d

0527869d Update readme
1ae8c84b Merge bugfix branch for stale subexternals into master.
b0c16d7c Bugfix: stale sub-externals after checkout.
30a4e442 Finish implementing system test for mixed-use externals
ac7ff962 Update mixed-use test repo.
bfda7b9c Bugfix: regexp for determining git tracking branches

git-subtree-dir: manage_externals
git-subtree-split: 0527869d2629c0430ee8e9ae404b2e865e97bec1
Commit:
fd3e069c588b6a2e84a53218f93aa4d43e67821b [fd3e069c]
Parents:
c843f07448
Author:
Ben Andre <andre@ucar.edu>
Date:
April 2, 2018 at 4:53:25 PM MDT
```

It's a subtle difference, but as I noted in the above link, using an annotated commit directly with subtree's can create problems with some versions of git the next time you try to update manage_externals. I would recommend following the above procedure and pulling in the underlying commit via a branch.

**Comment by ekluzek** [comment]
Yep, I did a pull to the annotated tag. If it's recommended to pull to a branch I can do that. I'm not sure why I couldn't find those instructions, as it's in an obvious place, but I didn't find them.

**Comment by bandre-ucar** [comment]
I've tagged v1.0.2 and pushed a release-v1.0 branch that should make it easier to pull in the latest tag. I'll add a release-v1.1 branch when I make the v1.1.0 tag.

**Comment by ekluzek** [comment]
OK, I reverted the commit that I did, and followed the steps on the same branch, but still didn't get the right thing going on this branch. So I created a fresh branch, that does seem to be correct and I'll create a new PR with it. It doesn't look like there is a way to update this PR with a new branch.

**Pull request closed without merging**
