### PR TITLE
Remove LILAC references to mct

### LINKED ISSUE #2294: use of mct_mod is deprecated
And must be removed prior to CESM3.
https://github.com/ESCOMP/CTSM/blob/master/lilac/src/lilac_mod.F90#L11

### PR DESCRIPTION
**Pull request by billsacks**
### Description of changes

Remove remaining references to mct. These appeared in two places:
- LILAC
- Unit tests

### Specific notes

Contributors other than yourself, if any: @jedwards4b identified these

CTSM Issues Fixed (include github issue #):
 Does one checkbox in #2294

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any:
Note: I ran the following testing with these changes off of ctsm5.1.dev167, then rebased the changes to the b4b-dev branch for the sake of this PR:
- LILACSMOKE_D_Ld2.f10_f10_mg37.I2000Ctsm50NwpSpAsRs.derecho_intel.clm-lilac: passes and bit-for-bit with ctsm5.1.dev167 (there were NLCOMP failures, but this looks like an issue with the baselines, since these changes shouldn't have impacted namelists at all)
- Fortran unit tests on my Mac (they currently aren't working on derecho so I couldn't run them there)

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]
@billsacks Thank you!

**Review by ekluzek — APPROVED** [review]
Looks great.

**Comment by ekluzek** [comment]
@billsacks I'm going to bring this in after #2385 so that it will bring in the fix for unit testing on Derecho. Then we'll be able to see the unit tests passing on Derecho.

**Comment by ekluzek** [comment]
Unit-testing now PASSes on Derecho with updated branch.

This also just resolves one checkbox in #2294. But, I'll bring it in as it is...

**Comment by ekluzek** [comment]
Testing ran as expected, so merging.

**Pull request merged**
