### PR TITLE
move from depricated shr_file to shr_log

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
This updates from the depricated shr_file_setLogunit to shr_log_setlogunit
### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?

Any User Interface Changes (namelist or namelist defaults changes)?

Does this create a need to change or add documentation? Did you do so?

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on derecho for intel/gnu and izumi for intel/gnu/nag/nvhpc is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by ekluzek** [comment]
We'll bring this in on the b4b-dev branch.

**Comment by samsrabin** [comment]
Relates to #2736.

**Review by samsrabin — APPROVED** [review]
Looks good! Thanks for fixing the trailing whitespace too. Now I just need to test.

**Comment by samsrabin** [comment]
I did most of the `aux_clm` suite today with okay results. However, there's a lot of work happening right now on b4b-dev with the beta03 cleanup, so I'm going to wait for that to settle down. Probably will pick this back up late in the week.

**Pull request merged**
