### PR TITLE
add smyle L83 compset and SSP3-7.0 extension

### LINKED ISSUE #738: Totvegc threshold used to zero out soil carbon upon exit_spinup needs to be revisited
### Brief summary of bug

The totvegc threshold that is used to zero out soil carbon stocks in areas where vegetation has died needs to be revisited.

### General bug information

**CTSM version you are using:** All versions

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** All BGC potentially

### Details of bug

This issue was first identified in March, 2019.  What follows is a recap of the issue from then to now.
We noticed large soil carbon stocks in regions where vegetation was dead in an emissions-driven simulation performed by Keith Lindsay.
We determined that these large soil carbon stocks were present because vegetation died sometime during the sequence of land-only spinups required to initialize the CMIP6 1850 pi_control:
cesm20exp10j_1deg_CPLHST_1850AD
cesm20exp10j_1deg_CPLHST_1850pAD
cesm20exp10j_1deg_CPLHST_nndep_1850pAD
cesm20exp10j_1deg_CPLHST_nndep_virtual_1850pAD

There is code in SoilBiogeochemCarbonStateType.F90 that was designed to prevent this that is executed during exit_spinup (transition from AD to normal mode):

                       ! If there is no vegetation carbon, implying that all vegetation has died, then
                       ! reset decomp pools to near zero during exit_spinup to avoid very
                       ! large and inert soil carbon stocks; note that only pools with spinup factor > 1
                       ! will be affected, which means that total SOMC and LITC pools will not be set to 0.
                       if (totvegc_col(c) <= this%totvegcthresh .and. lun%itype(l) /= istcrop) then
                         this%decomp_cpools_vr_col(c,j,k) = 0.0_r8
                       endif

However, the current setting of totvegcthresh=0.1 gC/m2 may be too small to cover all cases (e.g., the threshold needed may be sensitive to different climates).

To allow the emissions-driven simulation to proceed we decided to screen the initial file being used by applying a script as follows:

; This script reads in an initial file and zeros out the following variables:
;  soil1c_vr, soil2c_vr, soil3c_vr, soil1n_vr, soil2n_vr, soil3n_vr
;  litr1c_vr, litr2c_vr, litr3c_vr, litr1n_vr, litr2n_vr, litr3n_vr
;  cwdc_vr, cwdn_vr
; under the following conditions:
;  totvegc_col <= 0.01
;  all column types except crops
;  latitude >= 60N

The script for this particular case is here:

/gpfs/fs1/p/cgd/tss/people/oleson/modify_initdata/modify_b.e21.B1850_BPRP.f09_g17.CMIP6-piControl.tst.004_soilcarbon.ncl

We now need to find a more robust setting for this threshold as we are seeing other simulations that have this problem (the 2deg runs, e.g., b.e20.B1850.f19_g17.release_cesm2_1_0.020).  Or develop a different approach.

### LINKED ISSUE #1036: ne30np4 1850 case fails because the fsurdat file is incorrect.
### Brief summary of bug

Chris Fischer found that ERP_D_Ld5.ne30_g16.I1850Clm50BgcCrop.cheyenne_intel.clm-default tests fail. It looks like the fsurdat file is incorrect when this is setup. This is in cesm2_2_alpha06a testing. So the problem likely came in on ctsm1.0.dev098.

### General bug information

**CTSM version you are using:** ctsm1.0.dev100

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** ne30_g16.I1850Clm50BgcCrop

### Details of bug

fsurdat points to the landuse timeseries file...

 fsurdat = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/landuse.timeseries_ne30np4_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c170824.nc'

### Important output or errors that show the problem

Shows error in reading the surfdat file...

> 0:(  143)  r10i3n26
> 109: pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:        1288 :
> 109: NetCDF: Invalid dimension ID or name
> 37: pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:        1288 :
> 37: NetCDF: Invalid dimension ID or name
> 73: pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:        1288 :
> 73: NetCDF: Invalid dimension ID or name
> 1: pio_support::pio_die:: myrank=          -1 : ERROR: nf_mod.F90:        1288 :
> 1: NetCDF: Invalid dimension ID or name
> 109:Image              PC                Routine            Line        Source
> 109:cesm.exe           00000000053E66BA  Unknown               Unknown  Unknown
> 109:cesm.exe           0000000004A0542E  pio_support_mp_pi         118  pio_support.F90
> 109:cesm.exe           0000000004A03718  pio_utils_mp_chec          59  pio_utils.F90
> 109:cesm.exe           00000000049CEC4E  nf_mod_mp_pio_inq        1288  nf_mod.F90
> 109:cesm.exe           0000000000CD3B0F  ncdio_pio_mp_ncd_         432  ncdio_pio.F90.in
> 109:cesm.exe           0000000000CD3CCA  ncdio_pio_mp_ncd_         465  ncdio_pio.F90.in
> 109:cesm.exe           0000000000E4753D  surfrdmod_mp_surf         486  surfrdMod.F90
> 109:cesm.exe           00000000009047A5  clm_initializemod         104  clm_initializeMod.F90

### LINKED ISSUE #1093: Problems with running fates_next_api on izumi
### Brief summary of bug

Jackie has had problems running on izumi of late with fates_next_api.
@jkshuman 

### General bug information

**CTSM version you are using:** release-clm5.0.30-143-gabcd5937

**Does this bug cause significantly incorrect results in the model's science?** No
**Configurations affected:** izumi_intel

### Details of bug

Failure of building gptl.

### Important details of your setup / configuration so we can reproduce the bug

I think this is just because fates_next_api is using cime5.6.28 and needs to be updated to cime5.6.33

### Important output or errors that show the problem

> got another fail with gptl:
> 4:27
> Finished creating component namelists
> Building gptl with output to file /scratch/cluster/jkshuman/test2_Izu_GLDAS_boreal_GLDAS_0.25x_surf_0.125_6f568e42_e9f63270/bld/gptl.bldlog.200730-162622
>   Calling /home/jkshuman/git/fates_next_api/cime/src/build_scripts/buildlib.gptl
> ERROR: /home/jkshuman/git/fates_next_api/cime/src/build_scripts/buildlib.gptl FAILED, cat /scratch/cluster/jkshuman/test2_Izu_GLDAS_boreal_GLDAS_0.25x_surf_0.125_6f568e42_e9f63270/bld/gptl.bldlog.200730-162622
> 
> 
> 
> 
> 
> 4:28
> my case script is here in case it is another obvious error.
> 4:29
> path: /home/jkshuman/FATES_data/boreal/above_canada/case_izu_GLDAS_ABoVE_canada

### LINKED ISSUE #1131: Nitrogen Deposition file for SSP534OS
Per Mike Mills, the NorESM group requested that we generate forcing files from WACCM output for SSP5-3.4OS (b.e21.BWSSP534oscmip6.f09_g17.CMIP6-SSP5-3.4OS-WACCM.001).  Thus, Mike requested that I generate a nitrogen deposition file from this simulation.
It is here:
/glade/p/cgd/tss/people/oleson/CLM5_ndep/fndep_clm_SSP534OS_b.e21.BWSSP534oscmip6.f09_g17.CMIP6-SSP5-3.4OS-WACCM.001_2039-2101_monthly_0.9x1.25_c200831

The WACCM simulation was initialized at year 2040 and ran through year 2100, so I've created a file running from 2039-2101.
I'm not sure if this is needed/required by any other group (including CESM), but perhaps this should be placed in inputdata with the other ndep files.

I wasn't able to create a corresponding aerosol deposition file for land-only simulations because coupler history output wasn't saved in the WACCM simulation.  Alternatively, the file could be generated from a CAM simulation, but that simulation doesn't exist at present.

### LINKED ISSUE #1197: SMYLE use-case setup
Bring in a user-mod directory on the release-clm5.0 branch that implements the following for CLM:

https://docs.google.com/document/d/1rV3fWCIt-D1fAbzQ6uaQeZyLagzzKnopofr88eXegzY

### LINKED ISSUE #1578: Need to replace SSP370 ndep file with new one
### Brief summary of bug

Need to replace SSP370 ndep file with new one

### General bug information

**CTSM version you are using:** [output of `git describe`] N/A

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No] Maybe

**Configurations affected:** [Fill this in if known.]  Any that use SSP370 ndep file

### Details of bug

There was an error in landuse in b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.**001** (the landuse file was labeled SSP3-7, but in fact had SSP1-2.6 data in it).
A **002** simulation already partially run (which used the correct landuse file/data) was extended through 2100.
I generated a new ndep file from this extended **002** simulation:

/glade/p/cgd/tss/people/oleson/CLM5_ndep/fndep_clm_SSP370_b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.002_2014-2101_monthly_0.9x1.25_c211210.nc

The old ndep file was generated from the incorrect b.e21.BWSSP370cmip6.f09_g17.CMIP6-SSP3-7.0-WACCM.**001**.  Presumably, we will want to update our SSP370 namelists to the new file.

### LINKED ISSUE #1631: ndep file for SSP2-4.5 is incorrect
### Brief summary of bug

The ndep file for SSP2-4.5 that comes out of the box is SSP5-8.5.

### General bug information

**CTSM version you are using:** release-clm5.0.34

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** SSP2-4.5

### Details of bug

The file that gets set is:

lnd/clm2/ndepdata/fndep_clm_f09_g17.CMIP6-SSP5-8.5-WACCM_1849-2101_monthly_c191007.nc

What it should be is:

lnd/clm2/ndepdata/fndep_clm_f09_g17.CMIP6-SSP2-4.5-WACCM_1849-2101_monthly_c191007.nc

### LINKED ISSUE #1632: Missing ndep file to 2100 for CMIP6 SSP5-3.4
We currently don't have an out of the box ndep file for SSP5-3.4 to 2100. On release-clm5.0 we do have the extension from 2100-2300. There is a file that has 2039-2100

fndep_clm_SSP534OS_b.e21.BWSSP534oscmip6.f09_g17.CMIP6-SSP5-3.4OS-WACCM.001_2039-2101_monthly_0.9x1.25_c200831.nc

To match the other files we need to stitch it together with the historical period, and I believe the SSP5-8.5 scenario from 2015-2038. Then we could drop it in easily.

This is certainly the case on the release-clm5.0 branch, but must be the same on CTSM main-dev.

### LINKED ISSUE #1633: 2100 to 2500 Extension compset for SSP3-7.0
There is a need for a new extension compset for SSP3-7.0. For CLM we will have to do that by having fixed 2100 conditions. There isn't extension landuse data available for it. And of course WACCM has not been run for the extension so we will have to have fixed Nitrogen deposition.

The CESM documentation on this is here: 

https://github.com/ESCOMP/CESM/pull/203

The main thing to do is to setup compsets for this, and have a use-case that does fixed 2100 conditions.

### PR DESCRIPTION
**Pull request by jedwards4b**
### Description of changes
Adds a compset for the smyle L83 model.   BWsc1850smyle
### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
  Fixes #1197
  Fixes #1633 
  Fixes #1632 
  Fixes #1631 
  Fixes #1578  
  Fixes #1131 
  Fixes #1093 
  Fixes #1036 
  Fixes #738

Are answers expected to change (and if so in what way)? SSP3-7.0, SSP2-4.5 and SSP5-3.4 because of ndep files
   Except for when using the new smyle use-cases
   Spinup cases (such as the SSP tests) change answers because of #738

Any User Interface Changes (namelist or namelist defaults changes)? Addition of new smyle use-case

Testing performed, if any: regular testing will be done.

### CODE REVIEW

**Comment by ekluzek** [comment]
@jedwards4b thanks for putting this together and pointing us to it.

I have a question that I think is mainly for @billsacks.

This has history file settings in the use-case. Overall we've avoided doing that in CTSM, and put history settings either in build-namelist or in user-mod directories rather than use-cases. I'm not sure that putting them in a use-case is a bad thing to do -- just that we've avoided doing that. So I wanted to hear if anyone knows if there are reasons why not to put them in use-cases? It does potentially have problems if certain configurations turn off some of the history fields that are in the list. But, that would be OK, if the SMYLE use-case isn't going to be used in that situation. I asked the same question of the CAM folks also.

I do see that we did do this sort of thing for the use-case stdurbpt_pd.xml, but that's an uncommon case. For CMIP6 history settings we put those in user-mod directories. And we have some user-mod directories for high-frequency output as well.

**Comment by billsacks** [comment]
We decided to use user mods directories for other history file settings mostly because it makes it easier and less error-prone for users to customize the starting point: with a user mods directory, you have a user_nl_clm starting point that you can then change (adding or removing history fields as needed). This is more awkward and error-prone if you are setting history settings under the covers via a use case or namelist defaults.

**Comment by ekluzek** [comment]
Yes, that makes sense, and I think it would apply here. We could still have a use-case for some of the settings, but a user-mod directory for the history part of this. You are right that is the part that users are the most likely to mess with and change from one case to another.

**Comment by jedwards4b** [comment]
I have removed the history file changes to user_mods in https://github.com/jedwards4b/CESM2-Realtime-Forecast/
which is used to generate and run ensembles for the smyle experiment.

**Comment by jedwards4b** [comment]
I redid the use case as 20thC_smyle_transient.xml, however to avoid having to make changes to other components
I kept the compset name of BWsc1850smyle

**Comment by ekluzek** [comment]
Hey @jedwards4b I just want to send a "Are you sure"? cautionary note. :-) 

First it looks to me that we'll want to update the last years for some of the transient datasets being used. And actually I think we want to use the SSP scenario for some of these so that we have data beyond 2015.

The second concern is that do we really want to have some data transient for CLM, but fixed 1850 for other components? If that's correct, that's fine. If not we may want to change the compset even though it will require other components to change. It's also good to have our compsets follow the standard patterns, otherwise we end up having problems down the line when we forget about the exception we made.

It's just good to get this right, before simulations are run, even if that means a little more work up front.

**Pull request merged**
