### PR TITLE
Merge ctsm1.0.dev095 tag into fates_main_api

### PR DESCRIPTION
**Pull request by glemieux**
### Description of changes
This PR brings the fates_main_api branch up to date with [ctsm1.0.dev095 tag](https://github.com/ESCOMP/CTSM/releases/tag/ctsm1.0.dev095) to incorporate bug fixes to cime that cropped up during testing of fates_main_api.

### Specific notes

Contributors other than yourself, if any: @billsacks @ekluzek 

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?

Any User Interface Changes (namelist or namelist defaults changes)?

Testing performed, if any:
- [x] `fates` suite regression testing with baseline comparison

(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by glemieux** [comment]
This merge currently has an issue with the FATES lightning data use of logical variable `need_lightning_and_popdens` due to a conflict with its refactor from https://github.com/ESCOMP/CTSM/pull/1124/commits/59d1dd4a7267ed3cb681bef939b305dce113be8f.

I attempted to convert the variable call and data types in FATESFireDataMod and FATESFireNoDataMod, but quickly realized that this probably wouldn't work.  The relevant code is here: https://github.com/glemieux/ctsm/blob/4fdffa697195ae582e80b011a51de8b77b059f95/src/biogeochem/FATESFireDataMod.F90#L21-L55

The problem appears to be due to the fact that the logical value is trying to be referenced in a type that is two type extensions away from the `interface` definition.  @ekluzek, does that sound correct?  I don't have a lot of experience with interfaces.

**Comment by ekluzek** [comment]
@glemieux I can see what needs to happen in fates_fire_data_type. You remove the constructor, and add the logical data function as the other interfaces have. Make fates_fire_data_type look like the other types that extend from the same base class. Hopefully, that makes sense. If you need a quick call we could do that as well.

**Comment by glemieux** [comment]
> Make fates_fire_data_type look like the other types that extend from the same base class. Hopefully, that makes sense. If you need a quick call we could do that as well.

For the interface function part, are you saying that I should replicate the `need_lightning_and_popdens_interface` found in CNFireBaseMod in FatesFireBaseMod?

**Comment by glemieux** [comment]
Turns out the reason my interface updates to bring FateFireDataMod in line with the CNFireBaseMod refactor wasn't working was due to a simple problem due to the original merge not quite handling the change of a function to a subroutine.  Thanks @ekluzek!

Regression testing against baseline complete and all expected PASS:
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_ctsmdev095
```

**Comment by rgknox** [comment]
mostly looked through 725f9d6 to see what the fix was.  I didn't see any issues

**Pull request merged**
