### PR TITLE
Change CropPhenology to look at time as of the START of the time step

### PR DESCRIPTION
**Pull request by billsacks**
### Description of changes

The main change is to change CropPhenology to look at the time as of the START of the time step. Previously, CropPhenology looked at time as of the END of the time step. This was somewhat problematic, particularly because it meant that the last time step of the year was considered Jan 1, and so crops with a planting window beginning Jan 1 could be planted at the end of the previous year rather than the start of the new year. This was becoming particularly problematic in the context of Sam Rabin's upcoming prescribed sowing date work (see https://github.com/ESCOMP/CTSM/issues/1623 and https://github.com/ESCOMP/CTSM/pull/1616 for some discussion).

A supporting change is calling CropPhenology regardless of doalb – however, still not calling CropPhenology on time step 0. (See some discussion in https://github.com/ESCOMP/CTSM/issues/1626 and https://github.com/ESCOMP/CTSM/issues/1623 .)

### Specific notes

Contributors other than yourself, if any: @samsrabin

CTSM Issues Fixed (include github issue #):
- Resolves ESCOMP/CTSM#1623

Are answers expected to change (and if so in what way)? YES - answer changes expected for crop cases, though they should be small.

Any User Interface Changes (namelist or namelist defaults changes)? NO

Testing performed, if any: none yet

### CODE REVIEW

**Comment by billsacks** [comment]
@ekluzek @slevisconsulting @danicalombardozzi @samsrabin - I would welcome reviews from any or all of you if you'd like - mainly for the sake of helping to think about what might break due to these changes. (@samsrabin I can't formally request a review from you, but I'd welcome one anyway.)

**Comment by samsrabin** [comment]
Looks good to me, and merging it in didn't affect my sowing/harvest results (compared with  `get_curr_calday(offset = -1)`) in #1616.

**Comment by billsacks** [comment]
Based on conversations yesterday, if I understood correctly (please correct me if I'm wrong):
- @ekluzek said he might like to look at this, but don't hold it up waiting for him
- @danicalombardozzi said she couldn't think of any problems with it

Therefore, I am thinking of this as ready for final testing whenever it can come up next, unless anyone says otherwise.

**Comment by slevisconsulting** [comment]
> @ekluzek @slevisconsulting @danicalombardozzi @samsrabin - I would welcome reviews from any or all of you if you'd like - mainly for the sake of helping to think about what might break due to these changes. (@samsrabin I can't formally request a review from you, but I'd welcome one anyway.)

I only browsed through these code changes and have no concerns at this time. Thanks @billsacks for this work.

**Pull request merged**
