### PR TITLE
Renaming, correcting, simplifying parameters dewmx and sno_stor_max

### LINKED ISSUE #710: fcansno shouldn't depend on dewmx
In the parameter extraction of ctsm1.0.dev040, this code in CanopyHydrologyMod.F90:

```Fortran
                   dewmxi  = 1.0_r8/dewmx(p)
                   fcansno(p) = ((dewmxi/(vegt*6.0_r8*10.0_r8))*snocan(p))**0.15_r8 ! must match snocanmx 
```

was changed to:

```Fortran
                   dewmxi  = 1.0_r8/params_inst%dewmx  ! wasteful division
                   fcansno(p) = ((dewmxi / (vegt * params_inst%sno_stor_max * 10.0_r8)) * snocan(p))**0.15_r8 ! must match snocanmx 
```

However, this looks wrong to me: I think this should be simply:

```Fortran
                   fcansno(p) = ((1._r8 / (vegt * params_inst%sno_stor_max)) * snocan(p))**0.15_r8 ! must match snocanmx 
```

i.e., fcansno should only depend on `sno_stor_max`, not on `dewmx`. (And that change would agree with `snocanmx` earlier in the module.)

Currently, the two give the same answers because dewmx is set to 0.1 on the paramfile. But if someone changed dewmx, they would inadvertently change fcansno, which I think would not be what they intended.

@slevisconsulting can you look at this and decide if you agree, and if so, make a small tag with this change at some point. (Or it could be combined with other changes, but I have a feeling this could change answers by roundoff, so it might be best to isolate this.)

### PR DESCRIPTION
**Pull request by slevisconsulting**
### Description of changes

Rename
dewmx to liq_canopy_storage_scalar
sno_stor_max to sno_canopy_storage_scalar

Change snocanmx, liqcanmx, and fcansno to...
`snocanmx = params_inst%snow_canopy_storage_scalar(p) * (elai(p) + esai(p))`
`liqcanmx = params_inst%liq_canopy_storage_scalar(p) * (elai(p) + esai(p))`
`fcansno(p) = (snocan(p) / (vegt * params_inst%sno_stor_max))**0.15_r8`

### Specific notes

Contributors other than yourself, if any:
@billsacks @swensosc 

CTSM Issues Fixed (include github issue #):
fixes #710 

Are answers expected to change (and if so in what way)?
Roundoff

Any User Interface Changes (namelist or namelist defaults changes)?
New clm45 and clm50 param files to include the new names

Testing performed, if any:
./create_test ERS_D_Ld10.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-rm_indiv_lunits_and_collapse_to_dom -c ctsm1.0.dev041
and
./create_test ERS_D_Ld6.f10_f10_musgs.I1850Clm45BgcCrop.cheyenne_intel.clm-clm50CMIP6frc -c ctsm1.0.dev041
both PASS

### CODE REVIEW

**Comment by slevisconsulting** [comment]
When I merged tag ctsm1.0.dev041, I backed out the answer-changing mods of the 2 commits preceding the merge. So now I'm running the complete test-suite on cheyenne to confirm bfb before proceeding with the other changes.

**Comment by slevisconsulting** [comment]
Cheyenne test-suite PASSed as expected.

**Comment by slevisconsulting** [comment]
The last commit modifies 2 lines of code that result in round-off changes. Please review that I made the correct modifications.

**Comment by ekluzek** [comment]
@slevisconsulting is this completed then? I'll pull it to master if so.

**Comment by slevisconsulting** [comment]
Ran these commands successfully now:
./rimport -file lnd/clm2/paramdata/clm5_params.c190518.nc
./rimport -file lnd/clm2/paramdata/clm_params.c190518.nc

If the ChangeLog is approved, then I think that this PR is ready to merge.

**Pull request merged**
