### PR TITLE
Change hard-coded soil layers in phenology to use a target depth

### PR DESCRIPTION
**Pull request by billsacks**
### Description of changes

Adds infrastructure for finding the soil layer containing a given depth (covered by unit tests).

In phenology code, replaces hard-coded level 3 with a target soil depth. This value is read from the parameter file.

This is important for the sake of supporting flexible soil layers, as in the NWP configuration.

Also, some cleanup of the CNPhenology parameter reading code.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
- Resolves ESCOMP/ctsm#952

Are answers expected to change (and if so in what way)? YES. Configurations using the default soil layer structures for CLM45 and CLM50 will be bit-for-bit. But this will change answers for some configurations using other soil layer structures, including the NWP configuration, and possibly VIC.

Any User Interface Changes (namelist or namelist defaults changes)? New parameter file with one new parameter

Here are the diffs from `ncdump -p 7,19` of the new vs. old parameter files:

```diff
--- dump_old	2020-04-02 15:39:34.000000000 -0600
+++ dump_new	2020-04-02 15:39:42.000000000 -0600
@@ -1,4 +1,4 @@
-netcdf clm5_params.c190829 {
+netcdf clm5_params.c200402 {
 dimensions:
 	pft = 79 ;
 	segment = 4 ;
@@ -736,6 +736,10 @@
 		pftpar31:units = "degrees_Celsius" ;
 		pftpar31:_FillValue = 1000. ;
 		pftpar31:coordinates = "pftname" ;
+	double phenology_soil_depth ;
+		phenology_soil_depth:long_name = "Soil depth used for measuring states for phenology triggers" ;
+		phenology_soil_depth:units = "m" ;
+		phenology_soil_depth:comment = "Chosen to maintain current behavior with both CLM45 and CLM50 (layer 3)" ;
 	double planting_temp(pft) ;
 		planting_temp:long_name = "Average 10 day temperature needed for planting" ;
 		planting_temp:units = "K" ;
@@ -2767,6 +2771,8 @@
     _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
     _, _, _, _, _, _, _, _, _, _, _ ;
 
+ phenology_soil_depth = 0.080000000000000002 ;
+
  planting_temp = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
     283.14999999999998, 283.14999999999998, 280.14999999999998, 
     280.14999999999998, _, _, 286.14999999999998, 286.14999999999998, 
```

```diff
--- dump_old_clm45	2020-04-02 15:39:48.000000000 -0600
+++ dump_new_clm45	2020-04-02 15:43:15.000000000 -0600
@@ -1,4 +1,4 @@
-netcdf clm_params.c190829 {
+netcdf clm_params.c200402 {
 dimensions:
 	pft = 79 ;
 	segment = 4 ;
@@ -719,6 +719,10 @@
 		pftpar31:units = "degrees_Celsius" ;
 		pftpar31:_FillValue = 1000. ;
 		pftpar31:coordinates = "pftname" ;
+	double phenology_soil_depth ;
+		phenology_soil_depth:long_name = "Soil depth used for measuring states for phenology triggers" ;
+		phenology_soil_depth:units = "m" ;
+		phenology_soil_depth:comment = "Chosen to maintain current behavior with both CLM45 and CLM50 (layer 3)" ;
 	double planting_temp(pft) ;
 		planting_temp:long_name = "Average 10 day temperature needed for planting" ;
 		planting_temp:units = "K" ;
@@ -2688,6 +2692,8 @@
     _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
     _, _, _, _, _, _, _, _, _, _, _ ;
 
+ phenology_soil_depth = 0.080000000000000002 ;
+
  planting_temp = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
     283.14999999999998, 283.14999999999998, 280.14999999999998, 
     280.14999999999998, _, _, 286.14999999999998, 286.14999999999998, 
```

Testing performed, if any: Ran these tests with comparison against baseline:
- SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm50BgcCropQianRsGs.bishorn_gnu.clm-default
- SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm45BgcCropQianRsGs.bishorn_gnu.clm-default

### CODE REVIEW

**Comment by billsacks** [comment]
@ekluzek @wwieder - please let me know if you'd like me to wait for a review from you or if you don't feel a need to review this.

@lmbirch89 - once this is merged to master, we'll ask that you change #947 to use this new parameter rather than hard-coding level 3.

@barlage @slevisconsulting - I also want to call this to your attention: We realized that, in the NWP configuration, phenological triggers were using soil level 3, which for the NWP configuration is quite deep. This PR changes these phenological triggers to instead look at the top soil level (0 - 10 cm) in the NWP configuration. I'm not sure how much of a difference this will make.

**Comment by barlage** [comment]
@billsacks just to be clear on the comment you directed at me, the code locates the level dynamically and it just happens to be in the top layer for the NWP configuration (i.e., it's not hard coded to the top layer).

**Comment by billsacks** [comment]
> @billsacks just to be clear on the comment you directed at me, the code locates the level dynamically and it just happens to be in the top layer for the NWP configuration (i.e., it's not hard coded to the top layer).

Yes, sorry that was unclear. I'm currently setting the default at 8 cm, which falls in the top soil layer for the NWP configuration (0 - 10 cm).

**Comment by billsacks** [comment]
@barlage and @slevisconsulting - actually, I think you're using SP for most (all?) of your NWP runs, right? In that case, this fix won't have any impact on your simulations.

**Pull request merged**
